// .conflict-side-1/src/features/workspaces/WorkspaceOverview.svelte
<script lang="ts">
	import { createQueries, createQuery } from "@tanstack/svelte-query";
	import {
		AlertTriangle,
		Boxes,
		Cable,
		FolderOpen,
		GitBranch,
		GitCompareArrows,
		Layers,
		Pin,
		Clock3,
	} from "lucide-svelte";
	import FriendlyError from "@/components/FriendlyError.svelte";
	import {
		Alert,
		AlertDescription,
		AlertTitle,
		Badge,
		Button,
		Card,
		CardContent,
		CardDescription,
		CardHeader,
		CardTitle,
		Empty,
		EmptyDescription,
		EmptyHeader,
		EmptyTitle,
		Separator,
		Spinner,
	} from "@/components/ui/svelte";
	import {
		buildWorkspaceFetchKeys,
		buildWorkspaceFetchPlans,
		fetchWorkspaceResources,
	} from "@/features/workspaces/query";
	import { queryKeys } from "@/lib/queryKeys";
	import {
		createTauriClient,
		detectArgoCD,
		detectFlux,
		listArgoApplications,
		listFluxResources,
		listKubeContexts,
		listNamespaces,
		listResourceKinds,
	} from "@/lib/tauri";
	import type { FluxResourceSummary, ResourceSummary } from "@/lib/types";
	import {
		normalizeEntryPoints,
		resourceFromEntryPoint,
		type WorkspaceEntryPoint,
	} from "@/lib/workspace-entry-points";
	import {
		buildWorkspaceCompareEntries,
		buildWorkspaceCompareSummaries,
		buildWorkspaceHealthSummary,
		computeRestoreStatus,
		resourceKindLabel,
		workspaceClusterGroupLabel,
		workspaceScopeContexts,
		type SavedWorkspace,
		type WorkspaceShortcut,
	} from "@/lib/workspaces";
	import type { HealthFilter } from "@/features/resources/helpers";
	import type { IncidentFilter } from "@/features/incidents";
	import type { WorkspaceReadContext } from "@/lib/workspaceReadContext";

	let {
		workspace,
		workspaceReadContext,
		onOpenResources,
		onOpenResource,
		onReconcileEntryPoints,
		onOpenArgo,
		onOpenIncidents,
		onOpenPortForwards,
		onOpenLauncher,
	}: {
		workspace: SavedWorkspace;
		workspaceReadContext: WorkspaceReadContext;
		onOpenResources: (
			namespace?: string,
			initialSearch?: string,
			initialGitOpsFilter?: string,
			initialHealthFilter?: HealthFilter,
		) => void;
		onOpenResource: (resource: ResourceSummary) => void;
		onReconcileEntryPoints: (
			resources: ResourceSummary[],
			coverage: ReturnType<typeof buildWorkspaceFetchPlans>,
		) => void;
		onOpenArgo: (argoApp?: string, namespace?: string) => void;
		onOpenIncidents: (filter?: IncidentFilter) => void;
		onOpenPortForwards: () => void;
		onOpenLauncher: () => void;
	} = $props();

	const client = createTauriClient();

	const sourceReady = $derived(workspaceReadContext.sourceReady);
	const kubeconfigSourceKey = $derived(workspaceReadContext.kubeconfigSourceKey);
	const workspaceContextKey = $derived(workspaceScopeContexts(workspace.scope).join("|"));

	const contextsQuery = createQuery(() => ({
		queryKey: queryKeys.kubeContexts(kubeconfigSourceKey),
		queryFn: () => listKubeContexts(client, kubeconfigSourceKey),
		enabled: sourceReady,
	}));
	const contexts = $derived(contextsQuery.data ?? []);
	const clusterAvailable = $derived(
		contextsQuery.isPending ||
			contexts.some((context) => context.name === workspace.scope.clusterContext),
	);

	const namespacesQuery = createQuery(() => ({
		queryKey: queryKeys.namespaces(workspace.scope.clusterContext, kubeconfigSourceKey),
		queryFn: () => listNamespaces(client, workspace.scope.clusterContext, kubeconfigSourceKey),
		enabled: sourceReady && clusterAvailable && !contextsQuery.isPending,
		retry: false,
	}));
	const namespaces = $derived((namespacesQuery.data ?? []).map((namespace) => namespace.name));

	const kindsQuery = createQuery(() => ({
		queryKey: queryKeys.resourceKinds(workspace.scope.clusterContext, kubeconfigSourceKey),
		queryFn: () => listResourceKinds(client, workspace.scope.clusterContext, kubeconfigSourceKey),
		enabled: sourceReady && clusterAvailable && !contextsQuery.isPending,
		retry: false,
	}));
	const discoveredKinds = $derived(kindsQuery.data ?? []);

	const restoreStatus = $derived(
		computeRestoreStatus(workspace, contexts, namespaces, discoveredKinds),
	);
	const availableNamespaces = $derived(
		workspace.scope.namespaces.filter(
			(namespace) => !restoreStatus.missingNamespaces.includes(namespace),
		),
	);
	const workspaceFetchKeys = $derived(
		buildWorkspaceFetchKeys(workspace.scope, availableNamespaces),
	);
	const workspaceFetchCoverage = $derived(
		buildWorkspaceFetchPlans(workspace.scope, availableNamespaces),
	);

	const resourcesQuery = createQuery(() => ({
		queryKey: queryKeys.resources(workspaceContextKey, workspaceFetchKeys, kubeconfigSourceKey),
		queryFn: () => fetchWorkspaceResources(workspace.scope, availableNamespaces, kubeconfigSourceKey),
		enabled:
			sourceReady &&
			restoreStatus.clusterAvailable &&
			!namespacesQuery.isPending &&
			!kindsQuery.isPending,
		staleTime: 30_000,
	}));
	const rows = $derived(resourcesQuery.data ?? []);
	const entryPoints = $derived(normalizeEntryPoints(workspace.entryPoints));
	$effect(() => {
		if (resourcesQuery.isSuccess && !resourcesQuery.isPlaceholderData) {
			onReconcileEntryPoints(resourcesQuery.data ?? [], workspaceFetchCoverage);
		}
	});
	const health = $derived(buildWorkspaceHealthSummary(rows));
	const unhealthyCount = $derived(health.attention + health.degraded);
	const hasIncidentShortcuts = $derived(
		unhealthyCount > 0 || health.attention > 0 || health.restarted > 0,
	);

	const argoDetectedQuery = createQuery(() => ({
		queryKey: queryKeys.argoDetect(workspace.scope.clusterContext, kubeconfigSourceKey),
		queryFn: () => detectArgoCD(client, workspace.scope.clusterContext, kubeconfigSourceKey),
		enabled: sourceReady && restoreStatus.clusterAvailable,
	}));
	const fluxDetectedQuery = createQuery(() => ({
		queryKey: queryKeys.fluxDetect(workspace.scope.clusterContext, kubeconfigSourceKey),
		queryFn: () => detectFlux(client, workspace.scope.clusterContext, kubeconfigSourceKey),
		enabled: sourceReady && restoreStatus.clusterAvailable,
		staleTime: 60_000,
	}));
	const argoAppsQuery = createQuery(() => ({
		queryKey: queryKeys.argoApps(workspace.scope.clusterContext, kubeconfigSourceKey),
		queryFn: () => listArgoApplications(client, workspace.scope.clusterContext, kubeconfigSourceKey),
		enabled: argoDetectedQuery.data === true,
	}));
	const fluxResourceQueries = createQueries(() => ({
		queries: (fluxDetectedQuery.data?.kinds ?? []).map((kind) => ({
			queryKey: queryKeys.fluxResources(
				workspace.scope.clusterContext,
				kind,
				kubeconfigSourceKey,
			),
			queryFn: () => listFluxResources(client, workspace.scope.clusterContext, kind, kubeconfigSourceKey),
			enabled: fluxDetectedQuery.data?.detected === true,
			staleTime: 30_000,
		})),
	}));
	const argoDrift = $derived(
		(argoAppsQuery.data ?? []).filter((app) => app.syncStatus && app.syncStatus !== "Synced")
			.length,
	);
	const fluxDetected = $derived(fluxDetectedQuery.data?.detected === true);
	const fluxRows = $derived(
		fluxResourceQueries.flatMap((query) => (query.data as FluxResourceSummary[] | undefined) ?? []),
	);
	const fluxPending = $derived(
		fluxResourceQueries.length > 0 && fluxResourceQueries.some((query) => query.isPending),
	);
	const fluxError = $derived(fluxResourceQueries.find((query) => query.isError)?.error ?? null);
	const gitOpsInventoryError = $derived(argoAppsQuery.error ?? fluxError);
	const gitOpsDetected = $derived(argoDetectedQuery.data === true || fluxDetected);
	const gitOpsDetecting = $derived(argoDetectedQuery.isPending || fluxDetectedQuery.isPending);
	const hasRestoreWarning = $derived(
		contextsQuery.isSuccess &&
			(!restoreStatus.clusterAvailable ||
				restoreStatus.missingClusterContexts.length > 0 ||
				restoreStatus.missingNamespaces.length > 0 ||
				restoreStatus.missingKinds.length > 0),
	);
	const compareSummaries = $derived(
		buildWorkspaceCompareSummaries(buildWorkspaceCompareEntries(workspace.scope).slice(0, 2), rows),
	);

	function openShortcut(shortcut: WorkspaceShortcut) {
		if (shortcut.kind === "argo") {
			onOpenArgo(shortcut.argoApp);
			return;
		}
		onOpenResources(shortcut.namespace);
	}

	function openEntryPoint(entry: WorkspaceEntryPoint) {
		if (entry.kind === "namespace") {
			onOpenResources(entry.namespace ?? entry.name);
			return;
		}
		if (entry.kind === "app") {
			onOpenArgo(entry.name, entry.namespace);
			return;
		}
		const resource = resourceFromEntryPoint(entry);
		if (resource) onOpenResource(resource);
	}

	function entryPointLabel(entry: WorkspaceEntryPoint): string {
		if (entry.kind === "namespace") return `Namespace / ${entry.name}`;
		if (entry.kind === "app") return `Application / ${entry.name}`;
		return `${entry.resourceKind ?? "Resource"} / ${entry.name}`;
	}
</script>

<section class="mx-auto flex w-full max-w-7xl flex-col gap-4 p-4 md:p-6">
	<header class="border-b pb-3">
		<p class="text-[0.6875rem] font-semibold uppercase tracking-wide text-muted-foreground">
			Workspace Overview
		</p>
		<h1 class="mt-1 truncate text-lg font-semibold tracking-tight">{workspace.name}</h1>
		<div class="mt-2 flex flex-wrap gap-2">
			<Badge variant="outline" class="rounded-sm">{workspaceClusterGroupLabel(workspace.scope)}</Badge>
			<Badge variant="outline" class="rounded-sm">
				{workspace.scope.namespaces.length || "All"} namespaces
			</Badge>
			<Badge variant="outline" class="max-w-96 truncate rounded-sm">
				{workspace.scope.kinds.map(resourceKindLabel).join(", ")}
			</Badge>
		</div>
	</header>

	{#if hasRestoreWarning}
		<Alert class="border-amber-500/40 text-amber-200">
			<AlertTriangle class="size-3.5" />
			<AlertTitle>Unavailable saved scope</AlertTitle>
			<AlertDescription class="text-amber-200/90">
				{#if !restoreStatus.clusterAvailable}<div>Context missing: {workspace.scope.clusterContext}</div>{/if}
				{#if restoreStatus.missingClusterContexts.length > 0}
					<div>Group members: {restoreStatus.missingClusterContexts.join(", ")}</div>
				{/if}
				{#if restoreStatus.missingNamespaces.length > 0}
					<div>Namespaces: {restoreStatus.missingNamespaces.join(", ")}</div>
				{/if}
				{#if restoreStatus.missingKinds.length > 0}
					<div>Kinds: {restoreStatus.missingKinds.join(", ")}</div>
				{/if}
			</AlertDescription>
		</Alert>
	{/if}

	<Card size="sm" elevation="flat" class="overflow-hidden">
		<CardHeader class="border-b">
			<CardTitle>Resource Health</CardTitle>
			<CardDescription>Live status across saved workspace scope.</CardDescription>
		</CardHeader>
		<CardContent class="grid gap-3 pt-3">
			<div class="grid grid-cols-2 gap-2 md:grid-cols-5">
				{@render Metric("Total", health.total)}
				{@render Metric("Healthy", health.healthy, "text-emerald-300")}
				{@render Metric("Needs attention", health.attention, "text-amber-300")}
				{@render Metric("Degraded", health.degraded, "text-red-300")}
				{@render Metric("Restarted", health.restarted, "text-sky-300")}
			</div>

			{#if resourcesQuery.isPending}
				<div class="flex min-h-16 items-center justify-center gap-2 text-sm text-muted-foreground">
					<Spinner class="size-4" /> Loading workspace health...
				</div>
			{:else if resourcesQuery.isError}
				<FriendlyError
					mode="compact"
					error={resourcesQuery.error}
					context={{
						operation: "resourcesLoad",
						fallbackTitle: "Failed to refresh workspace resources",
						partial: true,
					}}
				/>
			{/if}

			{#if hasIncidentShortcuts}
				<div class="flex flex-wrap items-center gap-2 border-t pt-3">
					<span class="mr-1 text-xs font-medium text-muted-foreground">Incident shortcuts</span>
				{@render IncidentShortcutButton("Unhealthy", unhealthyCount, "unhealthy", onOpenIncidents)}
				{@render IncidentShortcutButton("Warnings", health.attention, "attention", onOpenIncidents)}
				{@render IncidentShortcutButton("Restarted", health.restarted, "restarted", onOpenIncidents)}
				</div>
			{/if}
		</CardContent>
	</Card>

	<Card size="sm" elevation="flat" class="overflow-hidden">
		<CardHeader class="border-b">
			<CardTitle>Operations</CardTitle>
			<CardDescription>Open primary workspace surfaces without changing scope.</CardDescription>
		</CardHeader>
		<CardContent class="grid gap-2 pt-3 sm:grid-cols-2 xl:grid-cols-4">
			<Button type="button" variant="outline" class="h-auto min-h-14 justify-start gap-3 px-4 py-3" onclick={() => onOpenResources()}>
				<Boxes class="size-4 shrink-0" /> Resources
			</Button>
			<Button type="button" variant="outline" class="h-auto min-h-14 justify-start gap-3 px-4 py-3" onclick={onOpenLauncher}>
				<FolderOpen class="size-4 shrink-0" /> Workspaces
			</Button>
			<Button type="button" variant="outline" class="h-auto min-h-14 justify-start gap-3 px-4 py-3" onclick={onOpenPortForwards}>
				<Cable class="size-4 shrink-0" /> Port Forwards
			</Button>
			<Button type="button" variant="outline" class="h-auto min-h-14 justify-start gap-3 px-4 py-3" onclick={onOpenIncidents}>
				<AlertTriangle class="size-4 shrink-0" /> Incidents
			</Button>
		</CardContent>
	</Card>

	<Card size="sm" elevation="flat" class="overflow-hidden">
		<CardHeader class="border-b">
			<CardTitle>Return to Work</CardTitle>
			<CardDescription>Saved and recent entry points for this workspace.</CardDescription>
		</CardHeader>
		<CardContent class="grid gap-3 pt-3 md:grid-cols-2 xl:grid-cols-[minmax(0,1fr)_minmax(0,1fr)_20rem]">
			<section class="overflow-hidden rounded-md border bg-background/30 md:col-span-2 xl:col-span-2">
				<header class="flex items-center justify-between gap-2 border-b px-3 py-2">
					<h2 class="text-sm font-semibold">Shortcuts</h2>
					<span class="text-xs tabular-nums text-muted-foreground">{workspace.shortcuts.length}</span>
				</header>
				<div class="flex min-h-16 flex-wrap items-start gap-2 p-3">
				{#if workspace.shortcuts.length === 0}
					<Empty class="min-h-20 w-full border-0">
						<EmptyHeader>
							<EmptyTitle>No shortcuts</EmptyTitle>
							<EmptyDescription>Workspace shortcuts appear after scope is saved.</EmptyDescription>
						</EmptyHeader>
					</Empty>
				{/if}
				{#each workspace.shortcuts as shortcut}
					<Button type="button" variant="outline" size="sm" onclick={() => openShortcut(shortcut)}>
						{#if shortcut.kind === "argo"}<GitBranch data-icon="inline-start" />
						{:else if shortcut.kind === "namespace"}<Layers data-icon="inline-start" />
						{:else if shortcut.kind === "compare"}<GitCompareArrows data-icon="inline-start" />
						{:else}<Boxes data-icon="inline-start" />{/if}
						{shortcut.label}
					</Button>
				{/each}
				</div>
			</section>

			<section class="overflow-hidden rounded-md border bg-background/30">
				<header class="border-b px-3 py-2">
					<h2 class="flex items-center gap-2 text-sm font-semibold"><Pin class="size-4" /> Pinned</h2>
					<p class="text-xs text-muted-foreground">Saved resource entry points.</p>
				</header>
				<div class="flex min-h-20 flex-wrap items-start gap-2 p-3">
					{#if entryPoints.pinned.length === 0}
						<span class="text-sm text-muted-foreground">Pin resources from the table or detail panel.</span>
					{/if}
					{#each entryPoints.pinned as entry}
						<Button type="button" variant="outline" size="sm" onclick={() => openEntryPoint(entry)}>
							<Pin data-icon="inline-start" /> {entryPointLabel(entry)}
						</Button>
					{/each}
				</div>
			</section>

			<section class="overflow-hidden rounded-md border bg-background/30">
				<header class="border-b px-3 py-2">
					<h2 class="flex items-center gap-2 text-sm font-semibold"><Clock3 class="size-4" /> Recent</h2>
					<p class="text-xs text-muted-foreground">Explicitly opened resources and scopes.</p>
				</header>
				<div class="flex min-h-20 flex-wrap items-start gap-2 p-3">
					{#if entryPoints.recent.length === 0}
						<span class="text-sm text-muted-foreground">Recent visits will appear here.</span>
					{/if}
					{#each entryPoints.recent as entry}
						<Button type="button" variant="outline" size="sm" onclick={() => openEntryPoint(entry)}>
							<Clock3 data-icon="inline-start" /> {entryPointLabel(entry)}
						</Button>
					{/each}
				</div>
			</section>

			<section class="overflow-hidden rounded-md border bg-background/30 md:col-span-2 xl:col-span-1 xl:col-start-3 xl:row-span-2 xl:row-start-1">
				<header class="border-b px-3 py-2">
					<h2 class="text-sm font-semibold">GitOps</h2>
					<p class="text-xs text-muted-foreground">Argo CD and Flux inventory.</p>
				</header>
				<div class="p-3">
				{#if gitOpsDetecting}
					<div class="inline-flex items-center gap-2 text-xs text-muted-foreground">
						<Spinner class="size-4" /> Detecting...
					</div>
				{:else if !gitOpsDetected}
					<div class="text-xs text-muted-foreground">Not detected</div>
				{:else}
					<div class="grid gap-2">
						{#if argoDetectedQuery.data === true && argoAppsQuery.isPending}
							<div class="inline-flex items-center gap-2 text-xs text-muted-foreground">
								<Spinner class="size-4" /> Loading applications...
							</div>
						{:else if gitOpsInventoryError}
							<FriendlyError
								mode="compact"
								error={gitOpsInventoryError}
								context={{
									operation: "providerDetection",
									fallbackTitle: "Failed to load GitOps inventory",
									partial: true,
								}}
							/>
						{:else if argoDetectedQuery.data === true}
							<div class="flex items-center justify-between py-2 text-xs">
								<span class="text-muted-foreground">Applications</span>
								<strong>{argoAppsQuery.data?.length ?? 0}</strong>
							</div>
							<Separator />
							<div class="flex items-center justify-between py-2 text-xs">
								<span class="text-muted-foreground">Out of sync</span>
								<strong class="text-amber-300">{argoDrift}</strong>
							</div>
							<Separator />
						{/if}
						{#if fluxDetected}
							{#if fluxPending}
								<div class="inline-flex items-center gap-2 text-xs text-muted-foreground">
									<Spinner class="size-4" /> Loading Flux resources...
								</div>
							{:else}
								<div class="flex items-center justify-between py-2 text-xs">
									<span class="text-muted-foreground">Flux resources</span>
									<strong>{fluxRows.length}</strong>
								</div>
								<Separator />
							{/if}
						{/if}
						<Button type="button" variant="outline" onclick={() => onOpenArgo()}>
							<GitBranch data-icon="inline-start" /> Open GitOps
						</Button>
					</div>
				{/if}
				</div>
			</section>
		</CardContent>
	</Card>

	{#if compareSummaries.length > 0}
		<Card>
			<CardHeader>
				<CardTitle>Compare</CardTitle>
				<CardDescription>Health split for saved workspace compare shortcuts.</CardDescription>
			</CardHeader>
			<CardContent class="grid gap-3 md:grid-cols-2">
				{#each compareSummaries as summary}
					<div class="rounded-md border bg-surface-1 p-3">
						<div class="text-sm font-medium">{summary.entry.label}</div>
						<div class="mt-2 grid grid-cols-2 gap-2 text-xs">
							{@render CompareSide(summary.entry.leftLabel, summary.left)}
							{@render CompareSide(summary.entry.rightLabel, summary.right)}
						</div>
					</div>
				{/each}
			</CardContent>
		</Card>
	{/if}
</section>

{#snippet Metric(label: string, value: string | number, tone = "")}
	<Card size="sm" class="min-h-20 justify-center">
		<CardContent class="flex flex-col gap-1">
			<span class="text-[0.72rem] font-semibold uppercase text-muted-foreground">{label}</span>
			<strong class={tone}>{value}</strong>
		</CardContent>
	</Card>
{/snippet}

{#snippet IncidentShortcutButton(label: string, count: number, filter: IncidentFilter, onOpenIncidents: (filter?: IncidentFilter) => void)}
	{#if count > 0}
		<Button type="button" variant="outline" size="sm" onclick={() => onOpenIncidents(filter)}>
			<AlertTriangle data-icon="inline-start" />
			{label}
			<Badge variant="secondary" class="ml-1 rounded-sm px-1.5 tabular-nums">{count}</Badge>
		</Button>
	{/if}
{/snippet}

{#snippet CompareSide(
	label: string,
	health: { total: number; healthy: number; attention: number; degraded: number; restarted: number },
)}
	<div class="rounded border bg-background p-2">
		<div class="truncate font-medium">{label}</div>
		<div class="mt-1 text-muted-foreground">
			{health.total} total / {health.healthy} healthy / {health.degraded + health.attention} flagged
		</div>
	</div>
{/snippet}

// src/features/workspaces/WorkspaceOverview.tsx
import { useMemo } from "react";
import { useQuery } from "@tanstack/react-query";
import {
	AlertTriangle,
	Boxes,
	Cable,
	FolderOpen,
	GitBranch,
	GitCompareArrows,
	Layers,
} from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
	Card,
	CardContent,
	CardDescription,
	CardHeader,
	CardTitle,
} from "@/components/ui/card";
import {
	Empty,
	EmptyDescription,
	EmptyHeader,
	EmptyTitle,
} from "@/components/ui/empty";
import { Separator } from "@/components/ui/separator";
import { Spinner } from "@/components/ui/spinner";
import { queryKeys } from "@/lib/queryKeys";
import { useSettingsState } from "@/lib/settings";
import {
	createTauriClient,
	detectArgoCD,
	listArgoApplications,
	listKubeContexts,
	listNamespaces,
	listResourceKinds,
} from "@/lib/tauri";
import {
	buildWorkspaceHealthSummary,
	computeRestoreStatus,
	resourceKindLabel,
	workspaceClusterGroupLabel,
	workspaceScopeContexts,
	type SavedWorkspace,
	type WorkspaceShortcut,
} from "@/lib/workspaces";
import type { HealthFilter } from "@/features/resources/helpers";
import { buildWorkspaceFetchKeys, fetchWorkspaceResources } from "./query";
import { WorkspaceComparePanel } from "./WorkspaceComparePanel";

const EMPTY_CONTEXTS: Awaited<ReturnType<typeof listKubeContexts>> = [];
const EMPTY_NAMESPACES: string[] = [];
const EMPTY_DISCOVERED_KINDS: Awaited<ReturnType<typeof listResourceKinds>> = [];
const EMPTY_RESOURCE_ROWS: Awaited<ReturnType<typeof fetchWorkspaceResources>> = [];

interface WorkspaceOverviewProps {
	workspace: SavedWorkspace;
	onOpenResources: (namespace?: string, healthFilter?: HealthFilter) => void;
	onOpenArgo: (argoApp?: string) => void;
	onOpenIncidents: () => void;
	onOpenPortForwards: () => void;
	onOpenLauncher: () => void;
}

function Metric({
	label,
	value,
	tone,
}: {
	label: string;
	value: number | string;
	tone?: string;
}) {
	return (
		<Card size="sm" className="min-h-20 justify-center">
			<CardContent className="flex flex-col gap-1">
			<span className="text-[0.72rem] font-semibold uppercase text-muted-foreground">
				{label}
			</span>
			<strong className={tone}>{value}</strong>
			</CardContent>
		</Card>
	);
}

function ShortcutButton({
	shortcut,
	onOpenResources,
	onOpenArgo,
}: {
	shortcut: WorkspaceShortcut;
	onOpenResources: (namespace?: string, healthFilter?: HealthFilter) => void;
	onOpenArgo: (argoApp?: string) => void;
}) {
	const icon =
		shortcut.kind === "argo" ? (
			<GitBranch />
		) : shortcut.kind === "namespace" ? (
			<Layers />
		) : shortcut.kind === "compare" ? (
			<GitCompareArrows />
		) : (
			<Boxes />
		);
	return (
		<Button
			type="button"
			variant="outline"
			size="sm"
			onClick={() =>
				shortcut.kind === "argo"
					? onOpenArgo(shortcut.argoApp)
					: onOpenResources(shortcut.namespace)
			}
		>
			{icon}
			{shortcut.label}
		</Button>
	);
}

function IncidentShortcutButton({
	label,
	count,
	onOpenIncidents,
}: {
	label: string;
	count: number;
	onOpenIncidents: () => void;
}) {
	if (count === 0) return null;
	return (
		<Button
			type="button"
			variant="outline"
			size="sm"
			onClick={onOpenIncidents}
		>
			<AlertTriangle data-icon="inline-start" />
			{label}
			<Badge variant="secondary" className="ml-1 rounded-sm px-1.5">
				{count}
			</Badge>
		</Button>
	);
}

export function WorkspaceOverview({
	workspace,
	onOpenResources,
	onOpenArgo,
	onOpenIncidents,
	onOpenPortForwards,
	onOpenLauncher,
}: WorkspaceOverviewProps) {
	const client = useMemo(() => createTauriClient(), []);
	const kubeconfigEnvVar = useSettingsState((state) => state.kubeconfigSourceKey);
	const contextsQuery = useQuery({
		queryKey: queryKeys.kubeContexts(kubeconfigEnvVar),
		queryFn: () => listKubeContexts(client, kubeconfigEnvVar),
	});
	const contexts = contextsQuery.data ?? EMPTY_CONTEXTS;
	const clusterAvailable =
		contextsQuery.isPending ||
		contexts.some((context) => context.name === workspace.scope.clusterContext);
	const workspaceContextKey = workspaceScopeContexts(workspace.scope).join("|");

	const namespacesQuery = useQuery({
		queryKey: queryKeys.namespaces(
			workspace.scope.clusterContext,
			kubeconfigEnvVar,
		),
		queryFn: () =>
			listNamespaces(client, workspace.scope.clusterContext, kubeconfigEnvVar),
		enabled: clusterAvailable && !contextsQuery.isPending,
	});
	const namespaces = useMemo(
		() =>
			namespacesQuery.data
				? namespacesQuery.data.map((namespace) => namespace.name)
				: EMPTY_NAMESPACES,
		[namespacesQuery.data],
	);

	const kindsQuery = useQuery({
		queryKey: queryKeys.resourceKinds(
			workspace.scope.clusterContext,
			kubeconfigEnvVar,
		),
		queryFn: () =>
			listResourceKinds(client, workspace.scope.clusterContext, kubeconfigEnvVar),
		enabled: clusterAvailable && !contextsQuery.isPending,
	});
	const discoveredKinds = kindsQuery.data ?? EMPTY_DISCOVERED_KINDS;

	const restoreStatus = useMemo(
		() =>
			computeRestoreStatus(
				workspace,
				contexts,
				namespaces,
				discoveredKinds,
			),
		[workspace, contexts, namespaces, discoveredKinds],
	);
	const availableNamespaces = workspace.scope.namespaces.filter(
		(namespace) => !restoreStatus.missingNamespaces.includes(namespace),
	);
	const workspaceFetchKeys = useMemo(
		() => buildWorkspaceFetchKeys(workspace.scope, availableNamespaces),
		[workspace.scope, availableNamespaces],
	);

	const resourcesQuery = useQuery({
		queryKey: queryKeys.resources(
			workspaceContextKey,
			workspaceFetchKeys,
			kubeconfigEnvVar,
		),
		queryFn: () =>
			fetchWorkspaceResources(
				workspace.scope,
				availableNamespaces,
				kubeconfigEnvVar,
			),
		enabled:
			restoreStatus.clusterAvailable &&
			!namespacesQuery.isPending &&
			!kindsQuery.isPending,
		staleTime: 30_000,
	});
	const rows = resourcesQuery.data ?? EMPTY_RESOURCE_ROWS;
	const health = useMemo(() => buildWorkspaceHealthSummary(rows), [rows]);

	const argoDetectedQuery = useQuery({
		queryKey: queryKeys.argoDetect(
			workspace.scope.clusterContext,
			kubeconfigEnvVar,
		),
		queryFn: () => detectArgoCD(client, workspace.scope.clusterContext, kubeconfigEnvVar),
		enabled: restoreStatus.clusterAvailable,
	});
	const argoAppsQuery = useQuery({
		queryKey: queryKeys.argoApps(
			workspace.scope.clusterContext,
			kubeconfigEnvVar,
		),
		queryFn: () =>
			listArgoApplications(client, workspace.scope.clusterContext, kubeconfigEnvVar),
		enabled: argoDetectedQuery.data === true,
	});
	const argoApps = argoAppsQuery.data;
	const argoDrift = (argoApps ?? []).filter(
		(app) => app.syncStatus && app.syncStatus !== "Synced",
	).length;
	const unhealthyCount = health.attention + health.degraded;
	const hasIncidentShortcuts =
		unhealthyCount > 0 || health.attention > 0 || health.restarted > 0;

	const hasRestoreWarning =
		!restoreStatus.clusterAvailable ||
		restoreStatus.missingClusterContexts.length > 0 ||
		restoreStatus.missingNamespaces.length > 0 ||
		restoreStatus.missingKinds.length > 0;

	return (
		<div className="mx-auto flex w-full max-w-6xl flex-col gap-4">
			<div className="flex flex-wrap items-center justify-between gap-3 border-b pb-3">
				<div className="min-w-0">
					<h1 className="truncate text-lg font-semibold">{workspace.name}</h1>
					<div className="mt-1 flex flex-wrap gap-2">
						<Badge variant="outline" className="rounded-sm">
							{workspaceClusterGroupLabel(workspace.scope)}
						</Badge>
						<Badge variant="outline" className="rounded-sm">
							{workspace.scope.namespaces.length || "All"} namespaces
						</Badge>
						<Badge variant="outline" className="rounded-sm">
							{workspace.scope.kinds.map(resourceKindLabel).join(", ")}
						</Badge>
					</div>
				</div>
				<div className="flex flex-wrap justify-end gap-2">
					<Button type="button" onClick={() => onOpenResources()}>
						<Boxes data-icon="inline-start" />
						Resources
					</Button>
					<Button type="button" variant="outline" onClick={onOpenLauncher}>
						<FolderOpen data-icon="inline-start" />
						Workspaces
					</Button>
					<Button type="button" variant="outline" onClick={onOpenPortForwards}>
						<Cable data-icon="inline-start" />
						Port Forwards
					</Button>
					<Button type="button" variant="outline" onClick={onOpenIncidents}>
						<AlertTriangle data-icon="inline-start" />
						Incidents
					</Button>
				</div>
			</div>

			{hasRestoreWarning && (
				<Alert className="border-amber-500/40 text-amber-200">
					<AlertTriangle className="size-3.5" />
					<AlertTitle>Unavailable saved scope</AlertTitle>
					<AlertDescription className="text-amber-200/90">
					{!restoreStatus.clusterAvailable && (
						<div>Context missing: {workspace.scope.clusterContext}</div>
					)}
					{restoreStatus.missingClusterContexts.length > 0 && (
						<div>
							Group members: {restoreStatus.missingClusterContexts.join(", ")}
						</div>
					)}
					{restoreStatus.missingNamespaces.length > 0 && (
						<div>Namespaces: {restoreStatus.missingNamespaces.join(", ")}</div>
					)}
					{restoreStatus.missingKinds.length > 0 && (
						<div>Kinds: {restoreStatus.missingKinds.join(", ")}</div>
					)}
					</AlertDescription>
				</Alert>
			)}

			<div className="grid grid-cols-1 gap-2 md:grid-cols-5">
				<Metric label="Total" value={health.total} />
				<Metric label="Healthy" value={health.healthy} tone="text-emerald-300" />
				<Metric label="Needs attention" value={health.attention} tone="text-amber-300" />
				<Metric label="Degraded" value={health.degraded} tone="text-red-300" />
				<Metric label="Restarted" value={health.restarted} tone="text-sky-300" />
			</div>

			{hasIncidentShortcuts && (
				<Card>
					<CardHeader>
						<CardTitle>Incident shortcuts</CardTitle>
						<CardDescription>
							Open Incident Cockpit for this workspace.
						</CardDescription>
					</CardHeader>
					<CardContent className="flex flex-wrap gap-2">
						<IncidentShortcutButton
							label="Unhealthy"
							count={unhealthyCount}
							onOpenIncidents={onOpenIncidents}
						/>
						<IncidentShortcutButton
							label="Warnings"
							count={health.attention}
							onOpenIncidents={onOpenIncidents}
						/>
						<IncidentShortcutButton
							label="Restarted"
							count={health.restarted}
							onOpenIncidents={onOpenIncidents}
						/>
					</CardContent>
				</Card>
			)}

			<div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_320px]">
				<Card>
					<CardHeader>
						<CardTitle>Shortcuts</CardTitle>
						<span className="text-xs text-muted-foreground">
							{workspace.shortcuts.length}
						</span>
					</CardHeader>
					<CardContent className="flex flex-wrap gap-2">
						{workspace.shortcuts.length === 0 && (
							<Empty className="min-h-32 border-0">
								<EmptyHeader>
									<EmptyTitle>No shortcuts</EmptyTitle>
									<EmptyDescription>
										Workspace shortcuts appear after scope is saved.
									</EmptyDescription>
								</EmptyHeader>
							</Empty>
						)}
						{workspace.shortcuts.map((shortcut) => (
							<ShortcutButton
								key={shortcut.id}
								shortcut={shortcut}
								onOpenResources={onOpenResources}
								onOpenArgo={onOpenArgo}
							/>
						))}
					</CardContent>
				</Card>
				<Card>
					<CardHeader>
						<CardTitle>Argo CD</CardTitle>
						<CardDescription>
							Application inventory for this cluster.
						</CardDescription>
					</CardHeader>
					<CardContent>
					{argoDetectedQuery.isPending && (
						<div className="inline-flex items-center gap-2 text-xs text-muted-foreground">
							<Spinner className="size-4" />
							Detecting&hellip;
						</div>
					)}
					{argoDetectedQuery.data === false && (
						<div className="text-xs text-muted-foreground">Not detected</div>
					)}
					{argoDetectedQuery.data === true && (
						<div className="grid gap-2">
							{argoAppsQuery.isPending && (
								<div className="inline-flex items-center gap-2 text-xs text-muted-foreground">
									<Spinner className="size-4" />
									Loading applications&hellip;
								</div>
							)}
							{argoAppsQuery.isError && (
								<Alert variant="destructive">
									<AlertTitle>Failed to load applications</AlertTitle>
									<AlertDescription>
										Application counts are unavailable until the next refresh.
									</AlertDescription>
								</Alert>
							)}
							{argoApps && (
								<>
									<div className="flex items-center justify-between py-2 text-xs">
										<span className="text-muted-foreground">Applications</span>
										<strong>{argoApps.length}</strong>
									</div>
									<Separator />
									<div className="flex items-center justify-between py-2 text-xs">
										<span className="text-muted-foreground">Out of sync</span>
										<strong className="text-amber-300">{argoDrift}</strong>
									</div>
									<Separator />
								</>
							)}
							<Button type="button" variant="outline" onClick={() => onOpenArgo()}>
								<GitBranch data-icon="inline-start" />
								Open Argo CD
							</Button>
						</div>
					)}
					</CardContent>
				</Card>
			</div>

			<WorkspaceComparePanel workspace={workspace} rows={rows} />

			{resourcesQuery.isError && (
				<Alert variant="destructive">
					<AlertTitle>Failed to refresh workspace resources</AlertTitle>
					<AlertDescription>
						Resource health may be stale until the next refresh succeeds.
					</AlertDescription>
				</Alert>
			)}
		</div>
	);
}
