// src/features/resource-detail/ExecTab.tsx
import "@xterm/xterm/css/xterm.css";

import { useEffect, useMemo, useRef, useState } from "react";
import { FitAddon } from "@xterm/addon-fit";
import { Terminal } from "@xterm/xterm";
import { Play, RotateCcw, Square, Terminal as TerminalIcon } from "lucide-react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import {
	Empty,
	EmptyDescription,
	EmptyHeader,
	EmptyTitle,
} from "@/components/ui/empty";
import {
	Field,
	FieldDescription,
	FieldGroup,
	FieldLabel,
} from "@/components/ui/field";
import { Label } from "@/components/ui/label";
import {
	Select,
	SelectContent,
	SelectGroup,
	SelectItem,
	SelectTrigger,
	SelectValue,
} from "@/components/ui/select";
import { Spinner } from "@/components/ui/spinner";
import { Textarea } from "@/components/ui/textarea";
import {
	closePodExecChannel,
	createPodExecChannel,
	listPodExecSessions,
	resizePodExecTerminal,
	startPodExecSession,
	stopPodExecSession,
	writePodExecStdin,
	type TauriClient,
} from "@/lib/tauri";
import { queryKeys } from "@/lib/queryKeys";
import { useSettingsState } from "@/lib/settings";
import type { PodExecSessionMessage, ResourceSummary } from "@/lib/types";
import { cn } from "@/lib/utils";
import type { ContainerStatusRow } from "./helpers";
import { getErrorMessage } from "./helpers";
import {
	buildPodExecRequest,
	commandForPreset,
	isPodExecForResource,
	podExecCommandText,
	podExecTarget,
	sortPodExecSessions,
	type PodExecPreset,
} from "./pod-exec-helpers";

interface ExecTabProps {
	client: TauriClient;
	resource: ResourceSummary;
	containers: ContainerStatusRow[];
	selectedContainer: string;
	onSelectedContainerChange: (container: string) => void;
	active: boolean;
}

const DEFAULT_COLS = 100;
const DEFAULT_ROWS = 32;

export function ExecTab({
	client,
	resource,
	containers,
	selectedContainer,
	onSelectedContainerChange,
	active,
}: ExecTabProps) {
	const queryClient = useQueryClient();
	const kubeconfigEnvVar = useSettingsState((state) => state.kubeconfigSourceKey);
	const showKubeconfigSourceLabels = useSettingsState(
		(state) => state.showKubeconfigSourceLabels,
	);
	const terminalHostRef = useRef<HTMLDivElement>(null);
	const terminalRef = useRef<Terminal | null>(null);
	const fitAddonRef = useRef<FitAddon | null>(null);
	const channelRef = useRef<ReturnType<typeof createPodExecChannel> | null>(null);
	const sessionIdRef = useRef<string | null>(null);
	const channelTokenRef = useRef(0);
	const [preset, setPreset] = useState<PodExecPreset>("sh");
	const [customArgv, setCustomArgv] = useState("");
	const [confirmed, setConfirmed] = useState(false);
	const [starting, setStarting] = useState(false);
	const [stoppingId, setStoppingId] = useState<string | null>(null);
	const [status, setStatus] = useState("idle");
	const [message, setMessage] = useState("Start an exec session to open the terminal.");
	const [error, setError] = useState<string | null>(null);
	const options = useMemo(() => {
		const regularContainers = containers.filter(
			(container) => container.type !== "init",
		);
		return regularContainers.length > 0 ? regularContainers : containers;
	}, [containers]);
	const sessionsQuery = useQuery({
		queryKey: queryKeys.podExecSessions(),
		queryFn: () => listPodExecSessions(client),
		enabled: active,
		refetchInterval: active ? 3_000 : false,
	});
	const sessions = useMemo(
		() =>
			sortPodExecSessions(
				(sessionsQuery.data ?? []).filter((session) =>
					isPodExecForResource(session, resource, kubeconfigEnvVar),
				),
			),
		[resource, sessionsQuery.data, kubeconfigEnvVar],
	);
	const command = commandForPreset(preset, customArgv);
	const commandText = typeof command === "string" ? "" : podExecCommandText(command);

	const closeCurrentSession = () => {
		channelTokenRef.current += 1;
		sessionIdRef.current = null;
		if (channelRef.current) {
			closePodExecChannel(channelRef.current);
			channelRef.current = null;
		}
	};

	useEffect(() => {
		if (!active || !terminalHostRef.current || terminalRef.current) return;
		const terminal = new Terminal({
			cursorBlink: true,
			convertEol: true,
			fontFamily: "var(--font-mono, ui-monospace, SFMono-Regular, Consolas, monospace)",
			fontSize: 12,
			theme: {
				background: "#101113",
				foreground: "#f4f4f5",
			},
		});
		const fitAddon = new FitAddon();
		terminal.loadAddon(fitAddon);
		terminal.open(terminalHostRef.current);
		terminal.onData((data) => {
			const sessionId = sessionIdRef.current;
			if (sessionId) void writePodExecStdin(client, sessionId, data);
		});
		terminal.onResize(({ cols, rows }) => {
			const sessionId = sessionIdRef.current;
			if (sessionId) {
				void resizePodExecTerminal(client, sessionId, { cols, rows });
			}
		});
		terminalRef.current = terminal;
		fitAddonRef.current = fitAddon;
		const fit = () => {
			try {
				fitAddon.fit();
			} catch {
				// The terminal host can be briefly detached while the detail panel resizes.
			}
		};
		const frame = window.requestAnimationFrame(fit);
		window.addEventListener("resize", fit);
		return () => {
			window.cancelAnimationFrame(frame);
			window.removeEventListener("resize", fit);
			terminal.dispose();
			terminalRef.current = null;
			fitAddonRef.current = null;
		};
	}, [active, client]);

	useEffect(() => {
		if (!active) return;
		const frame = window.requestAnimationFrame(() => {
			try {
				fitAddonRef.current?.fit();
			} catch {
				// Ignore transient layout states while the tab becomes visible.
			}
		});
		return () => window.cancelAnimationFrame(frame);
	}, [active]);

	useEffect(() => {
		const sessionId = sessionIdRef.current;
		return () => {
			closeCurrentSession();
			if (sessionId) void stopPodExecSession(client, sessionId);
		};
	}, [client]);

	if (resource.kind !== "Pod") {
		return (
			<Empty className="min-h-64 border-0">
				<EmptyHeader>
					<EmptyTitle>Exec starts from Pods</EmptyTitle>
					<EmptyDescription>
						Select an exact namespaced Pod before opening an exec session.
					</EmptyDescription>
				</EmptyHeader>
			</Empty>
		);
	}

	if (!resource.namespace) {
		return (
			<Alert variant="destructive">
				<AlertTitle>Namespace required</AlertTitle>
				<AlertDescription>
					Pod exec requires a namespaced Pod target.
				</AlertDescription>
			</Alert>
		);
	}

	const invalidateSessions = () =>
		queryClient.invalidateQueries({ queryKey: queryKeys.podExecSessions() });

	const handleMessage = (event: PodExecSessionMessage, token: number) => {
		if (token !== channelTokenRef.current) return;
		if (
			event.type !== "started" &&
			sessionIdRef.current &&
			event.sessionId !== sessionIdRef.current
		) {
			return;
		}
		if (event.type === "started") {
			if (
				sessionIdRef.current &&
				sessionIdRef.current !== event.sessionId
			) {
				return;
			}
			sessionIdRef.current = event.sessionId;
			setStatus(event.summary.status);
			return;
		}
		if (event.type === "status") {
			setStatus(event.status);
			setMessage(event.message);
			return;
		}
		if (event.type === "output") {
			terminalRef.current?.write(event.data);
			return;
		}
		if (event.type === "error") {
			setStatus("error");
			setError(event.message);
			terminalRef.current?.writeln(`\r\n${event.message}`);
			closeCurrentSession();
			void invalidateSessions();
			return;
		}
		if (event.type === "exited") {
			setStatus("exited");
			setMessage(
				event.exitCode === undefined
					? "Exec session exited"
					: `Exec session exited with code ${event.exitCode}`,
			);
			closeCurrentSession();
			void invalidateSessions();
			return;
		}
		if (event.type === "stopped") {
			setMessage("Exec session stopped");
			closeCurrentSession();
			void invalidateSessions();
		}
	};

	const startSession = async () => {
		setError(null);
		const terminal = terminalRef.current;
		const request = buildPodExecRequest(
			resource,
			{
				preset,
				customArgv,
				container: selectedContainer,
				cols: terminal?.cols ?? DEFAULT_COLS,
				rows: terminal?.rows ?? DEFAULT_ROWS,
				confirmed,
			},
			kubeconfigEnvVar,
		);
		if (typeof request === "string") {
			setError(request);
			return;
		}
		const previousSessionId = sessionIdRef.current;
		closeCurrentSession();
		if (previousSessionId) {
			await stopPodExecSession(client, previousSessionId);
		}
		setStarting(true);
		setStatus("starting");
		setMessage("Starting exec session");
		terminal?.clear();
		terminal?.writeln(
			`Starting ${commandText} on ${podExecTarget(resource, selectedContainer)}\r\n`,
		);
		const channelToken = channelTokenRef.current + 1;
		channelTokenRef.current = channelToken;
		const channel = createPodExecChannel((event) =>
			handleMessage(event, channelToken),
		);
		channelRef.current = channel;
		try {
			const summary = await startPodExecSession(client, request, channel);
			sessionIdRef.current = summary.id;
			await invalidateSessions();
		} catch (err) {
			closePodExecChannel(channel);
			channelRef.current = null;
			setStatus("error");
			setError(getErrorMessage(err));
		} finally {
			setStarting(false);
		}
	};

	const stopSession = async (sessionId: string) => {
		setStoppingId(sessionId);
		try {
			const isActiveSession = sessionIdRef.current === sessionId;
			if (isActiveSession) closeCurrentSession();
			await stopPodExecSession(client, sessionId);
			if (isActiveSession) {
				setStatus("stopped");
			}
			await invalidateSessions();
		} finally {
			setStoppingId(null);
		}
	};

	return (
		<div className="flex h-full min-h-0 flex-col gap-4">
			<Alert>
				<TerminalIcon className="size-3.5" />
				<AlertTitle>Guarded Pod exec</AlertTitle>
				<AlertDescription>
					Exec is limited to this exact Pod and runs through the Kubernetes API.
				</AlertDescription>
			</Alert>
			<FieldGroup>
				<Field>
					<FieldLabel htmlFor="pod-exec-container">Container</FieldLabel>
					<Select
						value={selectedContainer}
						onValueChange={(container) => {
							onSelectedContainerChange(container);
							setConfirmed(false);
						}}
					>
						<SelectTrigger id="pod-exec-container" className="w-full">
							<SelectValue placeholder="Default container" />
						</SelectTrigger>
						<SelectContent>
							<SelectGroup>
								{options.map((container) => (
									<SelectItem key={container.name} value={container.name}>
										{container.name}
									</SelectItem>
								))}
							</SelectGroup>
						</SelectContent>
					</Select>
					<FieldDescription>
						Kubernetes chooses the default only when no container is selected.
					</FieldDescription>
				</Field>
				<Field>
					<FieldLabel htmlFor="pod-exec-command">Command</FieldLabel>
					<Select
						value={preset}
						onValueChange={(value) => {
							setPreset(value as PodExecPreset);
							setConfirmed(false);
						}}
					>
						<SelectTrigger id="pod-exec-command" className="w-full">
							<SelectValue />
						</SelectTrigger>
						<SelectContent>
							<SelectGroup>
								<SelectItem value="sh">/bin/sh</SelectItem>
								<SelectItem value="bash">/bin/bash</SelectItem>
								<SelectItem value="custom">Custom argv</SelectItem>
							</SelectGroup>
						</SelectContent>
					</Select>
					<FieldDescription>
						Shell presets are exact commands; KubeCove does not fall back.
					</FieldDescription>
				</Field>
				{preset === "custom" && (
					<Field data-invalid={Boolean(error?.includes("argv"))}>
						<FieldLabel htmlFor="pod-exec-custom-argv">Custom argv</FieldLabel>
						<Textarea
							id="pod-exec-custom-argv"
							value={customArgv}
							placeholder={"/usr/bin/env\nprintenv"}
							aria-invalid={Boolean(error?.includes("argv"))}
							onChange={(event) => {
								setCustomArgv(event.target.value);
								setConfirmed(false);
							}}
						/>
						<FieldDescription>
							Enter one argv item per line. This is not parsed as a local shell.
						</FieldDescription>
					</Field>
				)}
			</FieldGroup>
			<div className="rounded-md border bg-muted/20 p-3 text-xs">
				<div className="font-medium">Target</div>
				<div className="mt-1 font-mono text-muted-foreground">
					{podExecTarget(resource, selectedContainer)}
				</div>
				<div className="mt-3 font-medium">Command</div>
				<div className="mt-1 font-mono text-muted-foreground">
					{commandText || "Custom argv is required"}
				</div>
			</div>
			<Label
				htmlFor="pod-exec-confirm"
				className="gap-2 rounded-md border bg-background p-3 text-xs text-muted-foreground"
			>
				<Checkbox
					id="pod-exec-confirm"
					checked={confirmed}
					onCheckedChange={(checked) => setConfirmed(checked === true)}
				/>
				I understand this opens an interactive session in the selected Pod.
			</Label>
			{error && (
				<Alert variant="destructive">
					<AlertTitle>Exec session failed</AlertTitle>
					<AlertDescription>{error}</AlertDescription>
				</Alert>
			)}
			<div className="flex flex-wrap items-center justify-between gap-2">
				<Badge variant={status === "error" ? "destructive" : "outline"}>
					Exec: {status}
				</Badge>
				<div className="text-xs text-muted-foreground">{message}</div>
				<Button type="button" onClick={() => void startSession()} disabled={starting}>
					{starting ? (
						<Spinner data-icon="inline-start" />
					) : (
						<Play data-icon="inline-start" />
					)}
					Start
				</Button>
			</div>
			<div
				ref={terminalHostRef}
				className={cn(
					"min-h-[280px] flex-1 overflow-hidden rounded-md border bg-background p-2",
					!active && "hidden",
				)}
			/>
			<div className="flex flex-col gap-2">
				<div className="flex items-center justify-between gap-3">
					<div className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
						Active exec sessions
					</div>
					{sessionsQuery.isFetching && <Spinner className="size-3.5" />}
				</div>
				{sessions.length === 0 ? (
					<Empty className="min-h-32 border-0">
						<EmptyHeader>
							<EmptyTitle>No exec sessions</EmptyTitle>
							<EmptyDescription>
								Start a guarded exec session for this Pod.
							</EmptyDescription>
						</EmptyHeader>
					</Empty>
				) : (
					<div className="flex flex-col gap-2">
						{sessions.map((session) => (
							<div
								key={session.id}
								className="flex flex-wrap items-center justify-between gap-2 rounded-md border bg-background p-3"
							>
								<div className="min-w-0">
									<div className="truncate font-mono text-xs">
										{podExecCommandText(session.command)}
									</div>
									<div className="truncate text-[11px] text-muted-foreground">
										{session.container
											? `Container ${session.container}`
											: "Default container"}
									</div>
									{showKubeconfigSourceLabels &&
										session.kubeconfigSourceLabel && (
											<div className="truncate text-[11px] text-muted-foreground">
												{session.kubeconfigSourceLabel}
											</div>
										)}
								</div>
								<div className="flex items-center gap-2">
									<Badge
										variant={
											session.status === "error" ? "destructive" : "outline"
										}
									>
										{session.status}
									</Badge>
									<Button
										type="button"
										variant="outline"
										size="sm"
										onClick={() => void stopSession(session.id)}
										disabled={stoppingId === session.id}
									>
										{stoppingId === session.id ? (
											<Spinner data-icon="inline-start" />
										) : (
											<Square data-icon="inline-start" />
										)}
										Stop
									</Button>
								</div>
							</div>
						))}
					</div>
				)}
			</div>
			<Button
				type="button"
				variant="outline"
				size="sm"
				onClick={() => terminalRef.current?.clear()}
			>
				<RotateCcw data-icon="inline-start" />
				Clear terminal
			</Button>
		</div>
	);
}

// src/features/resource-detail/ExecTab.svelte
<script lang="ts">
	import "@xterm/xterm/css/xterm.css";

	import { createQuery, useQueryClient } from "@tanstack/svelte-query";
	import { FitAddon } from "@xterm/addon-fit";
	import { Terminal as XtermTerminal } from "@xterm/xterm";
	import { onMount, tick } from "svelte";
	import { Play, RotateCcw, Square, Terminal as TerminalIcon } from "lucide-svelte";
	import FriendlyError from "@/components/FriendlyError.svelte";
	import {
		Alert,
		AlertDescription,
		AlertTitle,
		Badge,
		Button,
		Checkbox,
		Empty,
		EmptyDescription,
		EmptyHeader,
		EmptyTitle,
		Field,
		FieldDescription,
		FieldGroup,
		FieldLabel,
		Label,
		Select,
		SelectContent,
		SelectGroup,
		SelectItem,
		SelectTrigger,
		SelectValue,
		Spinner,
		Textarea,
	} from "@/components/ui/svelte";
	import { queryKeys } from "@/lib/queryKeys";
	import { settingsStore } from "@/lib/settings-store";
	import {
		closePodExecChannel,
		createPodExecChannel,
		listPodExecSessions,
		resizePodExecTerminal,
		startPodExecSession,
		stopPodExecSession,
		writePodExecStdin,
		type TauriClient,
	} from "@/lib/tauri";
	import type {
		PodExecSessionMessage,
		PodExecSessionSummary,
		ResourceSummary,
	} from "@/lib/types";
	import {
		buildPodExecRequest,
		commandForPreset,
		isPodExecForResource,
		podExecCommandText,
		podExecTarget,
		sortPodExecSessions,
		type PodExecPreset,
	} from "./pod-exec-helpers";
	import type { ContainerStatusRow } from "./helpers";

	const DEFAULT_COLS = 100;
	const DEFAULT_ROWS = 32;

	let {
		client,
		resource,
		containers,
		selectedContainer = $bindable(""),
		kubeconfigSourceKey,
		active,
	}: {
		client: TauriClient;
		resource: ResourceSummary;
		containers: ContainerStatusRow[];
		selectedContainer?: string;
		kubeconfigSourceKey?: string;
		active: boolean;
	} = $props();

	const queryClient = useQueryClient();
	let preset = $state<PodExecPreset>("sh");
	let customArgv = $state("");
	let confirmed = $state(false);
	let starting = $state(false);
	let stoppingId = $state<string | null>(null);
	let status = $state("idle");
	let message = $state("Start an exec session to open the terminal.");
	let error = $state<unknown>(null);
	let sessionId = $state<string | null>(null);
	let channel = $state<ReturnType<typeof createPodExecChannel> | null>(null);
	let terminalHost = $state<HTMLDivElement | null>(null);
	let terminal: XtermTerminal | null = null;
	let fitAddon: FitAddon | null = null;

	const isPod = $derived(resource.kind === "Pod" && Boolean(resource.namespace));
	const showKubeconfigSourceLabels = $derived(
		$settingsStore.showKubeconfigSourceLabels,
	);
	const containerOptions = $derived(
		containers.filter((container) => container.type !== "init").length > 0
			? containers.filter((container) => container.type !== "init")
			: containers,
	);
	const command = $derived(commandForPreset(preset, customArgv));
	const commandText = $derived(typeof command === "string" ? "" : podExecCommandText(command));

	const sessionsQuery = createQuery<PodExecSessionSummary[]>(() => ({
		queryKey: queryKeys.podExecSessions(),
		queryFn: () => listPodExecSessions(client),
		enabled: active,
		refetchInterval: active ? 3_000 : false,
	}));
	const sessions = $derived(
		sortPodExecSessions(
			(sessionsQuery.data ?? []).filter((session) =>
				isPodExecForResource(session, resource, kubeconfigSourceKey),
			),
		),
	);

	onMount(() => {
		if (terminalHost) {
			const nextTerminal = new XtermTerminal({
				cursorBlink: true,
				convertEol: true,
				fontFamily:
					"var(--font-mono, ui-monospace, SFMono-Regular, Consolas, monospace)",
				fontSize: 12,
				theme: {
					background: "#101113",
					foreground: "#f4f4f5",
				},
			});
			const nextFitAddon = new FitAddon();
			nextTerminal.loadAddon(nextFitAddon);
			nextTerminal.open(terminalHost);
			nextTerminal.onData((data) => {
				if (sessionId) void writePodExecStdin(client, sessionId, data);
			});
			nextTerminal.onResize(({ cols, rows }) => {
				if (sessionId) void resizePodExecTerminal(client, sessionId, { cols, rows });
			});
			terminal = nextTerminal;
			fitAddon = nextFitAddon;
			const fit = () => fitTerminal();
			const frame = window.requestAnimationFrame(fit);
			window.addEventListener("resize", fit);
			return () => {
				window.cancelAnimationFrame(frame);
				window.removeEventListener("resize", fit);
				if (channel) closePodExecChannel(channel);
				if (sessionId) void stopPodExecSession(client, sessionId);
				nextTerminal.dispose();
				terminal = null;
				fitAddon = null;
			};
		}
		return () => {
			if (channel) closePodExecChannel(channel);
			if (sessionId) void stopPodExecSession(client, sessionId);
		};
	});

	$effect(() => {
		if (!active) return;
		const frame = window.requestAnimationFrame(() => fitTerminal());
		return () => window.cancelAnimationFrame(frame);
	});

	function fitTerminal() {
		try {
			fitAddon?.fit();
		} catch {
			// Terminal can be hidden while tab/panel layout settles.
		}
	}

	function appendOutput(text: string) {
		terminal?.write(text);
	}

	function closeChannelOnly() {
		if (channel) closePodExecChannel(channel);
		channel = null;
		sessionId = null;
	}

	function handleMessage(event: PodExecSessionMessage) {
		if (event.type !== "started" && sessionId && event.sessionId !== sessionId) return;
		if (event.type === "started") {
			sessionId = event.sessionId;
			status = event.summary.status;
			return;
		}
		if (event.type === "status") {
			status = event.status;
			message = event.message;
			return;
		}
		if (event.type === "output") {
			appendOutput(event.data);
			return;
		}
		if (event.type === "error") {
			status = "error";
			error = event.message;
			appendOutput(`\n${event.message}\n`);
			closeChannelOnly();
			void queryClient.invalidateQueries({ queryKey: queryKeys.podExecSessions() });
			return;
		}
		if (event.type === "exited") {
			status = "exited";
			message =
				event.exitCode === undefined
					? "Exec session exited"
					: `Exec session exited with code ${event.exitCode}`;
			closeChannelOnly();
			void queryClient.invalidateQueries({ queryKey: queryKeys.podExecSessions() });
			return;
		}
		if (event.type === "stopped") {
			message = "Exec session stopped";
			closeChannelOnly();
			void queryClient.invalidateQueries({ queryKey: queryKeys.podExecSessions() });
		}
	}

	async function startSession() {
		error = null;
		await tick();
		fitTerminal();
		const request = buildPodExecRequest(
			resource,
			{
				preset,
				customArgv,
				container: selectedContainer,
				cols: terminal?.cols ?? DEFAULT_COLS,
				rows: terminal?.rows ?? DEFAULT_ROWS,
				confirmed,
			},
			kubeconfigSourceKey,
		);
		if (typeof request === "string") {
			error = request;
			return;
		}
		const previous = sessionId;
		closeChannelOnly();
		if (previous) await stopPodExecSession(client, previous);
		const nextChannel = createPodExecChannel(handleMessage);
		channel = nextChannel;
		starting = true;
		status = "starting";
		message = "Starting exec session";
		terminal?.clear();
		terminal?.writeln(
			`Starting ${commandText} on ${podExecTarget(resource, selectedContainer)}\r\n`,
		);
		try {
			const summary = await startPodExecSession(client, request, nextChannel);
			sessionId = summary.id;
			status = summary.status;
			await queryClient.invalidateQueries({ queryKey: queryKeys.podExecSessions() });
		} catch (err) {
			closePodExecChannel(nextChannel);
			if (channel === nextChannel) channel = null;
			status = "error";
			error = err;
		} finally {
			starting = false;
		}
	}

	async function stopSession(id: string) {
		stoppingId = id;
		try {
			if (sessionId === id) closeChannelOnly();
			await stopPodExecSession(client, id);
			await queryClient.invalidateQueries({ queryKey: queryKeys.podExecSessions() });
		} catch (err) {
			error = err;
		} finally {
			stoppingId = null;
		}
	}
</script>

{#if resource.kind !== "Pod"}
	<Empty class="min-h-32 border border-dashed">
		<EmptyHeader>
			<EmptyTitle>Exec starts from Pods</EmptyTitle>
			<EmptyDescription>Select an exact namespaced Pod before exec.</EmptyDescription>
		</EmptyHeader>
	</Empty>
{:else if !isPod}
	<Alert variant="destructive">
		<AlertTitle>Namespace required</AlertTitle>
		<AlertDescription>Pod exec requires a namespaced Pod target.</AlertDescription>
	</Alert>
{:else}
	<div class="flex flex-col gap-3">
		<Alert>
			<TerminalIcon />
			<AlertTitle>Guarded Pod exec</AlertTitle>
			<AlertDescription>Exec is limited to this exact Pod through the Kubernetes API.</AlertDescription>
		</Alert>

		<FieldGroup>
			<Field>
				<FieldLabel>Container</FieldLabel>
				<Select
					value={selectedContainer || "__default"}
					items={[
						{ value: "__default", label: "Default container" },
						...containerOptions.map((container) => ({
							value: container.name,
							label: container.name,
						})),
					]}
					onValueChange={(value: string) => {
						selectedContainer = value === "__default" ? "" : value;
						confirmed = false;
					}}
				>
					<SelectTrigger class="w-full">
						<SelectValue placeholder="Default container" />
					</SelectTrigger>
					<SelectContent>
						<SelectGroup>
							<SelectItem value="__default">Default container</SelectItem>
							{#each containerOptions as container (`${container.type}:${container.name}`)}
								<SelectItem value={container.name}>{container.name}</SelectItem>
							{/each}
						</SelectGroup>
					</SelectContent>
				</Select>
				<FieldDescription>Kubernetes chooses default only when no container is selected.</FieldDescription>
			</Field>
			<Field>
				<FieldLabel>Command</FieldLabel>
				<Select
					value={preset}
					items={[
						{ value: "sh", label: "/bin/sh" },
						{ value: "bash", label: "/bin/bash" },
						{ value: "custom", label: "Custom argv" },
					]}
					onValueChange={(value: string) => {
						preset = value as PodExecPreset;
						confirmed = false;
					}}
				>
					<SelectTrigger class="w-full">
						<SelectValue />
					</SelectTrigger>
					<SelectContent>
						<SelectGroup>
							<SelectItem value="sh">/bin/sh</SelectItem>
							<SelectItem value="bash">/bin/bash</SelectItem>
							<SelectItem value="custom">Custom argv</SelectItem>
						</SelectGroup>
					</SelectContent>
				</Select>
				<FieldDescription>Presets are exact commands; no local shell parsing.</FieldDescription>
			</Field>
			{#if preset === "custom"}
				<Field>
					<FieldLabel>Custom argv</FieldLabel>
					<Textarea
						bind:value={customArgv}
						placeholder={"/usr/bin/env\nprintenv"}
						oninput={() => (confirmed = false)}
					/>
					<FieldDescription>One argv item per line.</FieldDescription>
				</Field>
			{/if}
		</FieldGroup>

		<div class="rounded-md border bg-muted/20 p-3 text-xs">
			<div class="font-medium">Target</div>
			<div class="mt-1 break-words font-mono text-muted-foreground">
				{podExecTarget(resource, selectedContainer)}
			</div>
			{#if showKubeconfigSourceLabels && kubeconfigSourceKey}
				<div class="mt-2 font-medium">Kubeconfig source</div>
				<div class="mt-1 break-words font-mono text-muted-foreground">{kubeconfigSourceKey}</div>
			{/if}
			<div class="mt-3 font-medium">Command</div>
			<div class="mt-1 break-words font-mono text-muted-foreground">
				{commandText || "Custom argv is required"}
			</div>
		</div>

		<Label class="gap-2 rounded-md border bg-background p-3 text-xs text-muted-foreground">
			<Checkbox checked={confirmed} onCheckedChange={(checked) => (confirmed = checked)} />
			I understand this opens an interactive session in the selected Pod.
		</Label>

		{#if error}
			<FriendlyError
				error={error}
				context={{ operation: "exec", fallbackTitle: "Exec failed" }}
			/>
		{/if}

		<div class="flex flex-wrap items-center gap-2">
			<Badge variant={status === "error" ? "destructive" : "outline"}>Exec: {status}</Badge>
			<span class="text-xs text-muted-foreground">{message}</span>
			<Button onclick={startSession} disabled={starting}>
				{#if starting}
					<Spinner data-icon="inline-start" />
				{:else}
					<Play data-icon="inline-start" />
				{/if}
				Start
			</Button>
		</div>

		<div
			bind:this={terminalHost}
			class="min-h-[280px] overflow-hidden rounded-md border bg-background p-2"
			class:hidden={!active}
		></div>
		<div class="flex justify-end">
			<Button variant="outline" size="sm" onclick={() => terminal?.clear()}>
				<RotateCcw data-icon="inline-start" />
				Clear terminal
			</Button>
		</div>

		<div class="flex items-center justify-between gap-2">
			<div class="text-xs font-semibold uppercase text-muted-foreground">Active exec sessions</div>
			{#if sessionsQuery.isFetching}<Spinner />{/if}
		</div>
		{#if sessions.length === 0}
			<Empty class="min-h-24 border border-dashed">
				<EmptyHeader>
					<EmptyTitle>No exec sessions</EmptyTitle>
					<EmptyDescription>Start guarded exec for this Pod.</EmptyDescription>
				</EmptyHeader>
			</Empty>
		{:else}
			<div class="flex flex-col gap-2">
				{#each sessions as item (item.id)}
					<div class="flex flex-wrap items-center justify-between gap-2 rounded-md border bg-background p-3">
						<div class="min-w-0">
							<div class="truncate font-mono text-xs">{podExecCommandText(item.command)}</div>
							<div class="text-[11px] text-muted-foreground">
								{item.container ? `Container ${item.container}` : "Default container"}
							</div>
							{#if showKubeconfigSourceLabels && item.kubeconfigSourceLabel}
								<div class="truncate text-[11px] text-muted-foreground">
									{item.kubeconfigSourceLabel}
								</div>
							{/if}
						</div>
						<div class="flex items-center gap-2">
							<Badge variant={item.status === "error" ? "destructive" : "outline"}>{item.status}</Badge>
							<Button
								variant="outline"
								size="sm"
								onclick={() => stopSession(item.id)}
								disabled={stoppingId === item.id}
							>
								{#if stoppingId === item.id}
									<Spinner data-icon="inline-start" />
								{:else}
									<Square data-icon="inline-start" />
								{/if}
								Stop
							</Button>
						</div>
					</div>
				{/each}
			</div>
		{/if}
	</div>
{/if}
