// src/features/resource-detail/PortForwardTab.tsx
import { useMemo, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Cable, Copy, Play, Save, Square } from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
	Empty,
	EmptyDescription,
	EmptyHeader,
	EmptyTitle,
} from "@/components/ui/empty";
import {
	Field,
	FieldDescription,
	FieldGroup,
	FieldLabel,
} from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Separator } from "@/components/ui/separator";
import {
	Select,
	SelectContent,
	SelectGroup,
	SelectItem,
	SelectTrigger,
	SelectValue,
} from "@/components/ui/select";
import { Spinner } from "@/components/ui/spinner";
import {
	listPortForwards,
	startPodPortForward,
	stopPodPortForward,
	type TauriClient,
} from "@/lib/tauri";
import type { PortForwardSessionSummary, ResourceSummary } from "@/lib/types";
import { queryKeys } from "@/lib/queryKeys";
import { useSettingsState } from "@/lib/settings";
import { useWorkspaceStore, workspaceScopeContexts } from "@/lib/workspaces";
import { getErrorMessage } from "./helpers";
import {
	isPortForwardForResource,
	extractServicePortOptions,
	parsePortForwardForm,
	portForwardLocalUrl,
	sortPortForwardSessions,
} from "@/features/live-sessions/helpers";

interface PortForwardTabProps {
	client: TauriClient;
	resource: ResourceSummary;
	active: boolean;
	detailsYaml?: string;
}

type SaveMessage = {
	kind: "saved" | "duplicate";
	text: string;
};

async function copyText(text: string): Promise<void> {
	await navigator.clipboard?.writeText(text);
}

function sessionTitle(session: PortForwardSessionSummary): string {
	if (session.targetKind === "Service") {
		return `${session.localAddress}:${session.localPort} -> Service/${session.targetName}:${session.remotePort}`;
	}
	return `${session.localAddress}:${session.localPort} -> Pod/${session.targetName}:${session.remotePort}`;
}

function sessionResolution(session: PortForwardSessionSummary): string {
	if (session.targetKind === "Service") {
		return `Resolved to Pod/${session.resolvedPodName}:${session.resolvedPodPort}`;
	}
	return `Pod/${session.resolvedPodName}:${session.resolvedPodPort}`;
}

function isForwardableResource(resource: ResourceSummary): boolean {
	return resource.kind === "Pod" || resource.kind === "Service";
}

export function PortForwardTab({
	client,
	resource,
	active,
	detailsYaml,
}: PortForwardTabProps) {
	const queryClient = useQueryClient();
	const activeWorkspace = useWorkspaceStore(
		(state) =>
			state.workspaces.find(
				(workspace) => workspace.id === state.activeWorkspaceId,
			) ?? null,
	);
	const savePortForward = useWorkspaceStore((state) => state.savePortForward);
	const kubeconfigEnvVar = useSettingsState((state) => state.kubeconfigSourceKey);
	const showKubeconfigSourceLabels = useSettingsState(
		(state) => state.showKubeconfigSourceLabels,
	);
	const [remotePort, setRemotePort] = useState("");
	const [localPort, setLocalPort] = useState("");
	const [formError, setFormError] = useState<string | null>(null);
	const [startError, setStartError] = useState<string | null>(null);
	const [saveMessage, setSaveMessage] = useState<SaveMessage | null>(null);
	const [saveError, setSaveError] = useState<string | null>(null);
	const [starting, setStarting] = useState(false);
	const [stoppingId, setStoppingId] = useState<string | null>(null);
	const [copyingId, setCopyingId] = useState<string | null>(null);
	const { data: sessionsData, isFetching: sessionsFetching } = useQuery({
		queryKey: queryKeys.portForwards(),
		queryFn: () => listPortForwards(client),
		enabled: active,
		refetchInterval: active ? 3_000 : false,
	});
	const sessions = useMemo(
		() =>
			sortPortForwardSessions(
				(sessionsData ?? []).filter((session) =>
					isPortForwardForResource(session, resource, kubeconfigEnvVar),
				),
			),
		[resource, sessionsData, kubeconfigEnvVar],
	);
	const servicePortOptions = useMemo(
		() =>
			resource.kind === "Service"
				? extractServicePortOptions(detailsYaml)
				: [],
		[detailsYaml, resource.kind],
	);
	const selectedRemotePort =
		remotePort.trim() ||
		(resource.kind === "Service" && servicePortOptions[0]
			? String(servicePortOptions[0].port)
			: "");

	if (!isForwardableResource(resource)) {
		return (
			<Empty className="min-h-64 border-0">
				<EmptyHeader>
					<EmptyTitle>Port forwarding starts from Pods or Services</EmptyTitle>
					<EmptyDescription>
						Select a namespaced Pod or selector-backed Service.
					</EmptyDescription>
				</EmptyHeader>
			</Empty>
		);
	}

	if (!resource.namespace) {
		return (
			<Alert variant="destructive">
				<AlertTitle>Namespace required</AlertTitle>
				<AlertDescription>
					Port-forwarding requires a namespaced target.
				</AlertDescription>
			</Alert>
		);
	}
	const targetKind = resource.kind === "Service" ? "Service" : "Pod";

	const invalidateSessions = () =>
		queryClient.invalidateQueries({ queryKey: queryKeys.portForwards() });

	const startSession = async () => {
		setFormError(null);
		setStartError(null);
		setSaveMessage(null);
		setSaveError(null);
		const parsed = parsePortForwardForm(
			{ remotePort: selectedRemotePort, localPort },
			{ remotePortLabel: targetKind === "Service" ? "Service port" : "Pod port" },
		);
		if (typeof parsed === "string") {
			setFormError(parsed);
			return;
		}
		setStarting(true);
		try {
			await startPodPortForward(client, {
				clusterContext: resource.cluster,
				kubeconfigEnvVar,
				namespace: resource.namespace ?? "",
				targetKind,
				targetName: resource.name,
				podName: targetKind === "Pod" ? resource.name : undefined,
				remotePort: parsed.remotePort,
				localPort: parsed.localPort,
			});
			setLocalPort("");
			await invalidateSessions();
		} catch (err) {
			setStartError(getErrorMessage(err));
		} finally {
			setStarting(false);
		}
	};

	const saveServicePreset = () => {
		setFormError(null);
		setSaveMessage(null);
		setSaveError(null);
		if (targetKind !== "Service") return;
		if (!activeWorkspace) {
			setSaveError("Open a workspace before saving port-forward presets.");
			return;
		}
		const parsed = parsePortForwardForm(
			{ remotePort: selectedRemotePort, localPort },
			{ remotePortLabel: "Service port" },
		);
		if (typeof parsed === "string") {
			setFormError(parsed);
			return;
		}
		const workspaceContexts = workspaceScopeContexts(activeWorkspace.scope);
		if (!workspaceContexts.includes(resource.cluster)) {
			setSaveError(
				"Workspace context must include this Service before saving a preset.",
			);
			return;
		}
		const duplicate = (activeWorkspace.portForwards ?? []).some(
			(portForward) =>
				portForward.clusterContext === resource.cluster &&
				portForward.namespace === resource.namespace &&
				portForward.serviceName === resource.name &&
				portForward.servicePort === parsed.remotePort &&
				portForward.localPort === parsed.localPort,
		);
		if (duplicate) {
			setSaveMessage({
				kind: "duplicate",
				text: "This Service forward is already saved in the workspace.",
			});
			return;
		}
		savePortForward(activeWorkspace.id, {
			clusterContext: resource.cluster,
			namespace: resource.namespace ?? "",
			serviceName: resource.name,
			servicePort: parsed.remotePort,
			localPort: parsed.localPort,
		});
		setSaveMessage({
			kind: "saved",
			text: "Saved Service forward to this workspace.",
		});
	};

	const stopSession = async (sessionId: string) => {
		setStoppingId(sessionId);
		try {
			await stopPodPortForward(client, sessionId);
			await invalidateSessions();
		} finally {
			setStoppingId(null);
		}
	};

	const copySessionUrl = async (session: PortForwardSessionSummary) => {
		setCopyingId(session.id);
		try {
			await copyText(portForwardLocalUrl(session));
		} finally {
			setCopyingId(null);
		}
	};

	return (
		<div className="flex flex-col gap-4">
			<Alert>
				<Cable className="size-3.5" />
				<AlertTitle>Local {targetKind} tunnel</AlertTitle>
				<AlertDescription>
					KubeCove binds only to 127.0.0.1 and keeps sessions in memory.
					{targetKind === "Service"
						? " Services resolve once to a ready backing Pod."
						: ""}
				</AlertDescription>
			</Alert>
			<FieldGroup>
				<Field data-invalid={Boolean(formError?.includes("port"))}>
					<FieldLabel htmlFor="pod-port-forward-remote-port">
						{targetKind === "Service" ? "Service port" : "Pod port"}
					</FieldLabel>
					{targetKind === "Service" && servicePortOptions.length > 0 ? (
							<Select value={selectedRemotePort} onValueChange={setRemotePort}>
							<SelectTrigger
								id="pod-port-forward-remote-port"
								className="w-full"
								aria-invalid={Boolean(formError?.includes("port"))}
							>
								<SelectValue placeholder="Choose a Service port" />
							</SelectTrigger>
							<SelectContent>
								<SelectGroup>
									{servicePortOptions.map((option) => (
										<SelectItem
											key={`${option.port}:${option.name ?? ""}`}
											value={String(option.port)}
										>
											{option.name ? `${option.name} - ` : ""}
											{option.port}
											{option.targetPort
												? ` -> ${option.targetPort}`
												: ""}
										</SelectItem>
									))}
								</SelectGroup>
							</SelectContent>
						</Select>
					) : (
						<Input
							id="pod-port-forward-remote-port"
							inputMode="numeric"
							value={remotePort}
							placeholder="Required"
							aria-invalid={Boolean(formError?.includes("port"))}
							onChange={(event) => setRemotePort(event.target.value)}
						/>
					)}
					<FieldDescription>
						{targetKind === "Service"
							? servicePortOptions.length > 0
								? "Choose one of the TCP ports declared on this Service."
								: "The Service port Kubernetes should resolve to a backing Pod."
							: "The Pod port Kubernetes should forward to."}
					</FieldDescription>
				</Field>
				<Field>
					<FieldLabel htmlFor="pod-port-forward-local-port">
						Local port
					</FieldLabel>
					<Input
						id="pod-port-forward-local-port"
						inputMode="numeric"
						value={localPort}
						placeholder="Auto"
						onChange={(event) => setLocalPort(event.target.value)}
					/>
					<FieldDescription>
						Optional. Leave empty to choose an open localhost port.
					</FieldDescription>
				</Field>
			</FieldGroup>
			{formError && (
				<Alert variant="destructive">
					<AlertTitle>Check port values</AlertTitle>
					<AlertDescription>{formError}</AlertDescription>
				</Alert>
			)}
			{startError && (
				<Alert variant="destructive">
					<AlertTitle>Failed to start port forward</AlertTitle>
					<AlertDescription>{startError}</AlertDescription>
				</Alert>
			)}
			{saveError && (
				<Alert variant="destructive">
					<AlertTitle>Failed to save preset</AlertTitle>
					<AlertDescription>{saveError}</AlertDescription>
				</Alert>
			)}
			{saveMessage && (
				<Alert>
					<Save className="size-3.5" />
					<AlertTitle>
						{saveMessage.kind === "saved"
							? "Saved forward"
							: "Preset already saved"}
					</AlertTitle>
					<AlertDescription>{saveMessage.text}</AlertDescription>
				</Alert>
			)}
			<div className="flex flex-wrap justify-end gap-2">
				{targetKind === "Service" && (
					<Button
						type="button"
						variant="outline"
						onClick={saveServicePreset}
					>
						<Save data-icon="inline-start" />
						Save preset
					</Button>
				)}
				<Button type="button" onClick={() => void startSession()} disabled={starting}>
					{starting ? (
						<Spinner data-icon="inline-start" />
					) : (
						<Play data-icon="inline-start" />
					)}
					Start
				</Button>
			</div>
			<Separator />
			<div className="flex flex-col gap-3">
				<div className="flex items-center justify-between gap-3">
					<div className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
						Active sessions
					</div>
					{sessionsFetching && <Spinner className="size-3.5" />}
				</div>
				{sessions.length === 0 ? (
					<Empty className="min-h-40 border-0">
						<EmptyHeader>
							<EmptyTitle>No port forwards</EmptyTitle>
							<EmptyDescription>
								Start a tunnel to make this {targetKind} reachable on localhost.
							</EmptyDescription>
						</EmptyHeader>
					</Empty>
				) : (
					<div className="flex flex-col gap-2">
						{sessions.map((session) => {
							const localUrl = portForwardLocalUrl(session);
							return (
								<div
									key={session.id}
									className="flex flex-col gap-2 rounded-md border bg-background p-3"
								>
									<div className="flex min-w-0 items-center justify-between gap-2">
										<div className="min-w-0">
											<div className="truncate text-xs font-medium">
												{sessionTitle(session)}
											</div>
											<div className="truncate font-mono text-[11px] text-muted-foreground">
												{localUrl}
											</div>
											<div className="truncate text-[11px] text-muted-foreground">
												{sessionResolution(session)}
											</div>
											{showKubeconfigSourceLabels &&
												session.kubeconfigSourceLabel && (
													<div className="truncate text-[11px] text-muted-foreground">
														{session.kubeconfigSourceLabel}
													</div>
												)}
										</div>
										<Badge
											variant={
												session.status === "error" ? "destructive" : "outline"
											}
										>
											{session.status}
										</Badge>
									</div>
									{session.lastError && (
										<div className="text-xs text-destructive">
											{session.lastError}
										</div>
									)}
									<div className="flex flex-wrap justify-end gap-2">
										<Button
											type="button"
											variant="outline"
											size="sm"
											onClick={() => void copySessionUrl(session)}
											disabled={copyingId === session.id}
										>
											<Copy data-icon="inline-start" />
											Copy
										</Button>
										<Button
											type="button"
											variant="outline"
											size="sm"
											onClick={() => void stopSession(session.id)}
											disabled={stoppingId === session.id}
										>
											{stoppingId === session.id ? (
												<Spinner data-icon="inline-start" />
											) : (
												<Square data-icon="inline-start" />
											)}
											Stop
										</Button>
									</div>
								</div>
							);
						})}
					</div>
				)}
			</div>
		</div>
	);
}

// src/features/resource-detail/PortForwardTab.svelte
<script lang="ts">
	import { createQuery, useQueryClient } from "@tanstack/svelte-query";
	import { Cable, Copy, Play, Square } from "lucide-svelte";
	import {
		Alert,
		AlertDescription,
		AlertTitle,
		Badge,
		Button,
		Empty,
		EmptyDescription,
		EmptyHeader,
		EmptyTitle,
		Field,
		FieldDescription,
		FieldGroup,
		FieldLabel,
		Input,
		Select,
		SelectContent,
		SelectGroup,
		SelectItem,
		SelectTrigger,
		SelectValue,
		Spinner,
	} from "@/components/ui/svelte";
	import {
		isPortForwardForResource,
		extractServicePortOptions,
		parsePortForwardForm,
		portForwardLocalUrl,
		sortPortForwardSessions,
	} from "@/features/live-sessions/helpers";
	import { workspaceStore } from "@/features/workspaces/workspaceStore";
	import { queryKeys } from "@/lib/queryKeys";
	import { settingsStore } from "@/lib/settings-store";
	import {
		listPortForwards,
		startPodPortForward,
		stopPodPortForward,
		type TauriClient,
	} from "@/lib/tauri";
	import type {
		PortForwardSessionSummary,
		ResourceSummary,
	} from "@/lib/types";
	import { workspaceScopeContexts } from "@/lib/workspace-model";
	import { getErrorMessage } from "./helpers";

	let {
		client,
		resource,
		kubeconfigSourceKey,
		yaml,
		active,
	}: {
		client: TauriClient;
		resource: ResourceSummary;
		kubeconfigSourceKey?: string;
		yaml?: string;
		active: boolean;
	} = $props();

	const queryClient = useQueryClient();
	const selectedWorkspace = workspaceStore.selectedWorkspace;
	const showKubeconfigSourceLabels = $derived(
		$settingsStore.showKubeconfigSourceLabels,
	);
	let remotePort = $state("");
	let localPort = $state("");
	let starting = $state(false);
	let stoppingId = $state<string | null>(null);
	let copyingId = $state<string | null>(null);
	let error = $state("");
	let copyError = $state("");
	let saveMessage = $state("");
	let saveError = $state("");

	const targetSupported = $derived(
		(resource.kind === "Pod" || resource.kind === "Service") && Boolean(resource.namespace),
	);
	const servicePorts = $derived(extractServicePortOptions(yaml));
	const sessionsQuery = createQuery<PortForwardSessionSummary[]>(() => ({
		queryKey: queryKeys.portForwards(),
		queryFn: () => listPortForwards(client),
		enabled: active,
		refetchInterval: active ? 3_000 : false,
	}));
	const sessions = $derived(
		sortPortForwardSessions(
			(sessionsQuery.data ?? []).filter((session) =>
				isPortForwardForResource(session, resource, kubeconfigSourceKey),
			),
		),
	);

	$effect(() => {
		if (resource.kind === "Service" && !remotePort && servicePorts[0]) {
			remotePort = String(servicePorts[0].port);
		}
	});

	async function startForward() {
		error = "";
		copyError = "";
		saveError = "";
		const parsed = parsePortForwardForm(
			{ remotePort, localPort },
			{ remotePortLabel: resource.kind === "Service" ? "Service port" : "Pod port" },
		);
		if (typeof parsed === "string") {
			error = parsed;
			return;
		}
		if (!resource.namespace || !targetSupported) {
			error = "Pod or Service target with namespace is required";
			return;
		}
		starting = true;
		try {
			await startPodPortForward(client, {
				clusterContext: resource.cluster,
				kubeconfigEnvVar: kubeconfigSourceKey,
				namespace: resource.namespace,
				targetKind: resource.kind === "Service" ? "Service" : "Pod",
				targetName: resource.name,
				remotePort: parsed.remotePort,
				localPort: parsed.localPort,
			});
			localPort = "";
			await queryClient.invalidateQueries({ queryKey: queryKeys.portForwards() });
		} catch (err) {
			error = getErrorMessage(err);
		} finally {
			starting = false;
		}
	}

	function saveServicePreset() {
		error = "";
		saveMessage = "";
		saveError = "";
		if (resource.kind !== "Service") return;
		const activeWorkspace = $selectedWorkspace;
		if (!activeWorkspace) {
			saveError = "Open a workspace before saving port-forward presets.";
			return;
		}
		const parsed = parsePortForwardForm(
			{ remotePort, localPort },
			{ remotePortLabel: "Service port" },
		);
		if (typeof parsed === "string") {
			error = parsed;
			return;
		}
		if (!workspaceScopeContexts(activeWorkspace.scope).includes(resource.cluster)) {
			saveError = "Workspace context must include this Service before saving a preset.";
			return;
		}
		const duplicate = (activeWorkspace.portForwards ?? []).some(
			(portForward) =>
				portForward.clusterContext === resource.cluster &&
				portForward.namespace === resource.namespace &&
				portForward.serviceName === resource.name &&
				portForward.servicePort === parsed.remotePort &&
				portForward.localPort === parsed.localPort,
		);
		if (duplicate) {
			saveMessage = "Preset already saved for this Service.";
			return;
		}
		workspaceStore.saveSavedPortForward(activeWorkspace.id, {
			clusterContext: resource.cluster,
			namespace: resource.namespace ?? "",
			serviceName: resource.name,
			servicePort: parsed.remotePort,
			localPort: parsed.localPort,
		});
		saveMessage = "Saved Service forward to this workspace.";
	}

	async function stopForward(id: string) {
		copyError = "";
		stoppingId = id;
		try {
			await stopPodPortForward(client, id);
			await queryClient.invalidateQueries({ queryKey: queryKeys.portForwards() });
		} catch (err) {
			error = getErrorMessage(err);
		} finally {
			stoppingId = null;
		}
	}

	async function copySessionUrl(session: PortForwardSessionSummary) {
		copyingId = session.id;
		copyError = "";
		try {
			await navigator.clipboard?.writeText(portForwardLocalUrl(session));
		} catch (err) {
			copyError = getErrorMessage(err);
		} finally {
			copyingId = null;
		}
	}

	function sessionTitle(session: PortForwardSessionSummary): string {
		return `${session.localAddress}:${session.localPort} -> ${session.targetKind}/${session.targetName}:${session.remotePort}`;
	}

	function sessionResolution(session: PortForwardSessionSummary): string {
		if (session.targetKind === "Service") {
			return `Resolved to Pod/${session.resolvedPodName}:${session.resolvedPodPort}`;
		}
		return `Pod/${session.resolvedPodName}:${session.resolvedPodPort}`;
	}
</script>

{#if !targetSupported}
	<Empty class="min-h-32 border border-dashed">
		<EmptyHeader>
			<EmptyTitle>Port-forward unavailable</EmptyTitle>
			<EmptyDescription>Choose an exact namespaced Pod or Service target.</EmptyDescription>
		</EmptyHeader>
	</Empty>
{:else}
	<div class="flex flex-col gap-3">
		<Alert>
			<Cable />
			<AlertTitle>Guarded port-forward</AlertTitle>
			<AlertDescription>
				Target: {resource.namespace}/{resource.name} ({resource.kind})
			</AlertDescription>
		</Alert>

		<FieldGroup>
			{#if resource.kind === "Service" && servicePorts.length > 0}
				<Field>
					<FieldLabel>Service port</FieldLabel>
					<Select
						value={remotePort || String(servicePorts[0]?.port ?? "")}
						items={servicePorts.map((port) => ({
							value: String(port.port),
							label: port.name ? `${port.name} (${port.port})` : String(port.port),
						}))}
						onValueChange={(value: string) => (remotePort = value)}
					>
						<SelectTrigger class="w-full">
							<SelectValue placeholder="Service port" />
						</SelectTrigger>
						<SelectContent>
							<SelectGroup>
								{#each servicePorts as port (`${port.name ?? "port"}:${port.port}`)}
									<SelectItem value={String(port.port)}>
										{port.name ? `${port.name} (${port.port})` : port.port}
									</SelectItem>
								{/each}
							</SelectGroup>
						</SelectContent>
					</Select>
					<FieldDescription>TCP ports parsed from Service YAML.</FieldDescription>
				</Field>
			{:else}
				<Field>
					<FieldLabel>{resource.kind === "Service" ? "Service port" : "Pod port"}</FieldLabel>
					<Input bind:value={remotePort} inputmode="numeric" placeholder="8080" />
					<FieldDescription>Remote TCP port to forward.</FieldDescription>
				</Field>
			{/if}
			<Field>
				<FieldLabel>Local port</FieldLabel>
				<Input bind:value={localPort} inputmode="numeric" placeholder="auto" />
				<FieldDescription>Optional. Must be 1024 or higher when set.</FieldDescription>
			</Field>
		</FieldGroup>

		{#if error}
			<Alert variant="destructive">
				<AlertTitle>Port-forward failed</AlertTitle>
				<AlertDescription>{error}</AlertDescription>
			</Alert>
		{/if}
		{#if saveError}
			<Alert variant="destructive">
				<AlertTitle>Preset not saved</AlertTitle>
				<AlertDescription>{saveError}</AlertDescription>
			</Alert>
		{/if}
		{#if saveMessage}
			<Alert>
				<AlertTitle>Service preset</AlertTitle>
				<AlertDescription>{saveMessage}</AlertDescription>
			</Alert>
		{/if}
		{#if copyError}
			<Alert variant="destructive">
				<AlertTitle>Copy failed</AlertTitle>
				<AlertDescription>{copyError}</AlertDescription>
			</Alert>
		{/if}

		<div class="flex flex-wrap items-center gap-2">
			<Button onclick={startForward} disabled={starting}>
				{#if starting}
					<Spinner data-icon="inline-start" />
				{:else}
					<Play data-icon="inline-start" />
				{/if}
				Start
			</Button>
			{#if resource.kind === "Service"}
				<Button type="button" variant="outline" onclick={saveServicePreset}>Save preset</Button>
			{/if}
			<span class="text-xs text-muted-foreground">Local URL appears after session starts.</span>
		</div>

		<div class="flex items-center justify-between gap-2">
			<div class="text-xs font-semibold uppercase text-muted-foreground">Active port-forwards</div>
			{#if sessionsQuery.isFetching}<Spinner />{/if}
		</div>
		{#if sessions.length === 0}
			<Empty class="min-h-24 border border-dashed">
				<EmptyHeader>
					<EmptyTitle>No port-forwards</EmptyTitle>
					<EmptyDescription>Start a guarded session for this target.</EmptyDescription>
				</EmptyHeader>
			</Empty>
		{:else}
			<div class="flex flex-col gap-2">
				{#each sessions as session (session.id)}
					<div class="flex flex-wrap items-center justify-between gap-2 rounded-md border bg-background p-3">
						<div class="min-w-0">
							<div class="truncate text-xs font-medium">{sessionTitle(session)}</div>
							<div class="truncate font-mono text-xs text-muted-foreground">
								{portForwardLocalUrl(session)}
							</div>
							<div class="truncate text-xs text-muted-foreground">
								{sessionResolution(session)}
							</div>
							{#if showKubeconfigSourceLabels && session.kubeconfigSourceLabel}
								<div class="truncate text-xs text-muted-foreground">
									{session.kubeconfigSourceLabel}
								</div>
							{/if}
							{#if session.lastError}
								<div class="text-xs text-destructive">{session.lastError}</div>
							{/if}
						</div>
						<div class="flex items-center gap-2">
							<Badge variant={session.status === "error" ? "destructive" : "outline"}>
								{session.status}
							</Badge>
							<Button
								variant="outline"
								size="sm"
								onclick={() => copySessionUrl(session)}
								disabled={copyingId === session.id}
							>
								{#if copyingId === session.id}
									<Spinner data-icon="inline-start" />
								{:else}
									<Copy data-icon="inline-start" />
								{/if}
								Copy
							</Button>
							<Button
								variant="outline"
								size="sm"
								onclick={() => stopForward(session.id)}
								disabled={stoppingId === session.id}
							>
								{#if stoppingId === session.id}
									<Spinner data-icon="inline-start" />
								{:else}
									<Square data-icon="inline-start" />
								{/if}
								Stop
							</Button>
						</div>
					</div>
				{/each}
			</div>
		{/if}
	</div>
{/if}
