// src/components/NamespaceList.tsx
import { useQuery } from "@tanstack/react-query";
import { TimestampText } from "@/components/TimestampText";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Field, FieldLabel } from "@/components/ui/field";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Spinner } from "@/components/ui/spinner";
import { createTauriClient, listNamespaces } from "@/lib/tauri";
import { queryKeys } from "@/lib/queryKeys";
import { useSettingsState } from "@/lib/settings";
import { cn } from "@/lib/utils";

interface NamespaceListProps {
	clusterContext: string;
	selectedNamespaces: string[];
	onNamespaceChange: (namespaces: string[]) => void;
}

export function NamespaceList({
	clusterContext,
	selectedNamespaces,
	onNamespaceChange,
}: NamespaceListProps) {
	const kubeconfigEnvVar = useSettingsState((state) => state.kubeconfigSourceKey);
	const {
		data: namespaces = [],
		isPending: loading,
		isError,
		error,
		refetch,
	} = useQuery({
		queryKey: queryKeys.namespaces(clusterContext, kubeconfigEnvVar),
		queryFn: () =>
			listNamespaces(createTauriClient(), clusterContext, kubeconfigEnvVar),
		enabled: Boolean(clusterContext),
	});

	const handleToggleAll = () => {
		if (selectedNamespaces.length === namespaces.length) {
			onNamespaceChange([]);
		} else {
			onNamespaceChange(namespaces.map((ns) => ns.name));
		}
	};

	const handleToggleOne = (name: string) => {
		if (selectedNamespaces.includes(name)) {
			onNamespaceChange(selectedNamespaces.filter((namespace) => namespace !== name));
		} else {
			onNamespaceChange([...selectedNamespaces, name]);
		}
	};

	if (!clusterContext) {
		return (
			<div className="text-sm text-muted-foreground">
				Select a cluster context first
			</div>
		);
	}

	if (loading) {
		return (
			<div className="flex items-center gap-2 text-sm text-muted-foreground">
				<Spinner className="size-4" />
					Loading namespaces…
			</div>
		);
	}

	if (isError) {
		const errorMessage =
			error instanceof Error ? error.message : "Failed to load namespaces";
		return (
			<Alert variant="destructive">
				<AlertTitle>Failed to load namespaces</AlertTitle>
				<AlertDescription className="flex flex-col gap-2">
					<span>{errorMessage}</span>
					<Button
						type="button"
						variant="outline"
						size="sm"
						className="w-fit"
						onClick={() => void refetch()}
					>
						Retry
					</Button>
				</AlertDescription>
			</Alert>
		);
	}

	if (namespaces.length === 0) {
		return <div className="text-sm text-muted-foreground">No namespaces found</div>;
	}

	const allSelected =
		namespaces.length > 0 && selectedNamespaces.length === namespaces.length;

	return (
		<div className="flex min-h-0 flex-col">
			<div className="mb-3 flex items-center justify-between">
				<h3 className="m-0 text-xs font-semibold uppercase text-muted-foreground">
					Namespaces
				</h3>
				<Button
					onClick={handleToggleAll}
					type="button"
					variant="outline"
					size="sm"
					className="h-7 px-2 text-[0.625rem]"
				>
					{allSelected ? "Deselect All" : "Select All"}
				</Button>
			</div>
			<ScrollArea className="min-h-0 pr-2">
				<ul className="m-0 list-none p-0">
					{namespaces.map((namespace) => {
						const checked = selectedNamespaces.includes(namespace.name);
						const checkboxId = `namespace-${namespace.name}`;
						return (
							<li
								key={namespace.name}
								className={cn(
									"cursor-pointer rounded-md p-2 text-sm transition-colors hover:bg-accent",
									checked && "bg-accent",
								)}
							>
								<Field orientation="horizontal" className="items-center gap-2">
									<Checkbox
										id={checkboxId}
										checked={checked}
										onCheckedChange={() => handleToggleOne(namespace.name)}
									/>
									<FieldLabel
										htmlFor={checkboxId}
										className="min-w-0 flex-1 cursor-pointer font-normal"
									>
										<span className="flex-1 truncate">{namespace.name}</span>
										<TimestampText
											relative={namespace.age}
											exact={namespace.createdAt}
											className="text-xs text-muted-foreground outline-none focus-visible:rounded-sm focus-visible:ring-2 focus-visible:ring-ring/50"
										/>
									</FieldLabel>
								</Field>
							</li>
						);
					})}
				</ul>
			</ScrollArea>
		</div>
	);
}

// src/features/resources/NamespaceList.svelte
<script lang="ts">
	import { createQuery } from "@tanstack/svelte-query";
	import FriendlyError from "@/components/FriendlyError.svelte";
	import TimestampText from "@/components/TimestampText.svelte";
	import {
		Badge,
		Empty,
		EmptyDescription,
		EmptyHeader,
		EmptyTitle,
		Spinner,
		Table,
		TableBody,
		TableCell,
		TableHead,
		TableHeader,
		TableRow,
	} from "@/components/ui/svelte";
	import { queryKeys } from "@/lib/queryKeys";
	import { createTauriClient, listNamespaces } from "@/lib/tauri";
	import type { NamespaceSummary } from "@/lib/types";
	import type { WorkspaceReadContext } from "@/lib/workspaceReadContext";

	let { workspaceReadContext }: { workspaceReadContext: WorkspaceReadContext } = $props();

	const client = createTauriClient();
	const clusterContext = $derived(workspaceReadContext.clusterContext);
	const sourceReady = $derived(workspaceReadContext.sourceReady);
	const kubeconfigSourceKey = $derived(workspaceReadContext.kubeconfigSourceKey);
	const namespacesQuery = createQuery<NamespaceSummary[]>(() => ({
		queryKey: queryKeys.namespaces(clusterContext, kubeconfigSourceKey),
		queryFn: () => listNamespaces(client, clusterContext, kubeconfigSourceKey),
		enabled: Boolean(clusterContext) && sourceReady,
		retry: false,
	}));

	const namespaces = $derived(namespacesQuery.data ?? []);
	const namespaceError = $derived(
		workspaceReadContext.sourceError
			? workspaceReadContext.sourceError
			: namespacesQuery.isError
				? namespacesQuery.error
				: null,
	);
	const loading = $derived(Boolean(clusterContext) && (!sourceReady || namespacesQuery.isPending));
</script>

{#if !clusterContext}
	<Empty class="min-h-40 border border-dashed">
		<EmptyHeader>
			<EmptyTitle>No cluster context</EmptyTitle>
			<EmptyDescription>Select a workspace with a cluster context.</EmptyDescription>
		</EmptyHeader>
	</Empty>
{:else if namespaceError}
	<FriendlyError
		error={namespaceError}
		context={{ operation: "resourcesLoad", fallbackTitle: "Failed to load namespaces" }}
	/>
{:else if loading}
	<div class="flex min-h-40 items-center justify-center gap-2 text-xs text-muted-foreground">
		<Spinner />
		<span>Loading namespaces</span>
	</div>
{:else if namespaces.length === 0}
	<Empty class="min-h-40 border border-dashed">
		<EmptyHeader>
			<EmptyTitle>No namespaces found</EmptyTitle>
			<EmptyDescription>No namespaces returned for this context.</EmptyDescription>
		</EmptyHeader>
	</Empty>
{:else}
	<div class="flex flex-col gap-3">
		<div class="flex items-center justify-between gap-3">
			<div class="text-sm font-medium">Namespaces</div>
			<Badge variant="outline" class="tabular-nums">{namespaces.length}</Badge>
		</div>
		<Table aria-label="Namespaces">
			<TableHeader>
				<TableRow>
					<TableHead>Name</TableHead>
					<TableHead>Age</TableHead>
					<TableHead>Created</TableHead>
				</TableRow>
			</TableHeader>
			<TableBody>
				{#each namespaces as namespace (namespace.name)}
					<TableRow>
						<TableCell class="font-medium">{namespace.name}</TableCell>
						<TableCell>{namespace.age}</TableCell>
						<TableCell><TimestampText value={namespace.createdAt} relative={namespace.age} /></TableCell>
					</TableRow>
				{/each}
			</TableBody>
		</Table>
	</div>
{/if}
