// src/components/ClusterSelector.tsx
import { useEffect, useMemo } from "react";
import { useQuery } from "@tanstack/react-query";
import { createTauriClient, listKubeContexts } from "../lib/tauri";
import { queryKeys } from "@/lib/queryKeys";
import { useSettingsState } from "@/lib/settings";
import { Button } from "@/components/ui/button";
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

interface ClusterSelectorProps {
  value?: string;
  onClusterChange: (cluster: string) => void;
}

export function ClusterSelector({ value, onClusterChange }: ClusterSelectorProps) {
  const kubeconfigEnvVar = useSettingsState((state) => state.kubeconfigSourceKey);
  const {
    data: clusters = [],
    isPending: loading,
    isError,
    error,
    refetch,
  } = useQuery({
    queryKey: queryKeys.kubeContexts(kubeconfigEnvVar),
    queryFn: () => listKubeContexts(createTauriClient(), kubeconfigEnvVar),
  });

  const preferredContextName = useMemo(
    () => clusters.find((ctx) => ctx.isCurrent)?.name ?? clusters[0]?.name ?? "",
    [clusters],
  );
  const selectedValue = value ?? preferredContextName;

  useEffect(() => {
    if (!preferredContextName) return;
    const selectedStillExists = clusters.some((ctx) => ctx.name === value);
    if (!value || !selectedStillExists) {
      onClusterChange(preferredContextName);
    }
  }, [clusters, onClusterChange, preferredContextName, value]);

  const handleChange = (value: string) => {
    onClusterChange(value);
  };

  if (loading) {
    return (
      <div className="flex items-center gap-2 text-xs text-muted-foreground">
        Loading contexts…
      </div>
    );
  }

  if (isError) {
    const errorMessage =
      error instanceof Error ? error.message : "Failed to load contexts";
    return (
      <div className="flex items-center gap-2 text-xs text-destructive">
        Error: {errorMessage}
        <Button
          type="button"
          variant="outline"
          size="sm"
          onClick={() => void refetch()}
        >
          Retry
        </Button>
      </div>
    );
  }

  if (clusters.length === 0) {
    return <div className="text-xs text-muted-foreground">No contexts found</div>;
  }

  return (
    <div className="flex flex-row items-center gap-2">
      <span
        id="cluster-select-label"
        className="whitespace-nowrap text-[0.6875rem] font-bold uppercase tracking-wide text-muted-foreground"
      >
        Cluster Context:
      </span>
      <Select
        value={selectedValue}
        onValueChange={handleChange}
      >
        <SelectTrigger
          id="cluster-select"
          aria-labelledby="cluster-select-label"
          className="h-8 min-w-40 bg-background/50 text-xs"
        >
          <SelectValue placeholder="Select a context..." />
        </SelectTrigger>
        <SelectContent>
          <SelectGroup>
            {clusters.map((ctx) => (
              <SelectItem key={ctx.name} value={ctx.name}>
                {ctx.name}
              </SelectItem>
            ))}
          </SelectGroup>
        </SelectContent>
      </Select>
    </div>
  );
}

// src/components/ClusterSelector.svelte
<script lang="ts">
	import { createQuery } from "@tanstack/svelte-query";
	import {
		Button,
		Select,
		SelectContent,
		SelectGroup,
		SelectItem,
		SelectTrigger,
		SelectValue,
	} from "@/components/ui/svelte";
	import { queryKeys } from "@/lib/queryKeys";
	import { settingsStore } from "@/lib/settings-store";
	import { createTauriClient, listKubeContexts } from "@/lib/tauri";
	import type { ClusterContext } from "@/lib/types";

	let {
		value,
		onClusterChange,
	}: {
		value?: string;
		onClusterChange: (cluster: string) => void;
	} = $props();

	const client = createTauriClient();
	const kubeconfigSourceKey = $derived($settingsStore.kubeconfigSourceKey);
	const contextsQuery = createQuery<ClusterContext[]>(() => ({
		queryKey: queryKeys.kubeContexts(kubeconfigSourceKey),
		queryFn: () => listKubeContexts(client, kubeconfigSourceKey),
	}));

	const contexts = $derived(contextsQuery.data ?? []);
	const preferredContextName = $derived(
		contexts.find((context) => context.isCurrent)?.name ?? contexts[0]?.name ?? "",
	);
	const selectedValue = $derived(value ?? preferredContextName);
	const errorMessage = $derived(
		contextsQuery.error instanceof Error
			? contextsQuery.error.message
			: "Failed to load contexts",
	);

	$effect(() => {
		if (!preferredContextName) return;
		const selectedStillExists = contexts.some((context) => context.name === value);
		if (!value || !selectedStillExists) onClusterChange(preferredContextName);
	});
</script>

{#if contextsQuery.isPending}
	<div class="flex items-center gap-2 text-xs text-muted-foreground">
		Loading contexts...
	</div>
{:else if contextsQuery.isError}
	<div class="flex items-center gap-2 text-xs text-destructive">
		<span>Error: {errorMessage}</span>
		<Button type="button" variant="outline" size="sm" onclick={() => void contextsQuery.refetch()}>
			Retry
		</Button>
	</div>
{:else if contexts.length === 0}
	<div class="text-xs text-muted-foreground">No contexts found</div>
{:else}
	<div class="flex flex-row items-center gap-2">
		<span
			id="cluster-select-label"
			class="whitespace-nowrap text-[0.6875rem] font-bold uppercase tracking-wide text-muted-foreground"
		>
			Cluster Context:
		</span>
		<Select value={selectedValue} onValueChange={onClusterChange}>
			<SelectTrigger
				id="cluster-select"
				aria-labelledby="cluster-select-label"
				class="h-8 min-w-40 bg-background/50 text-xs"
			>
				<SelectValue placeholder="Select a context..." />
			</SelectTrigger>
			<SelectContent>
				<SelectGroup>
					{#each contexts as context (context.name)}
						<SelectItem value={context.name}>{context.name}</SelectItem>
					{/each}
				</SelectGroup>
			</SelectContent>
		</Select>
	</div>
{/if}
