// src/components/TimestampText.tsx
import type { ReactNode } from "react";
import {
	Tooltip,
	TooltipContent,
	TooltipTrigger,
} from "@/components/ui/tooltip";
import {
	useSettingsState,
} from "@/lib/settings";
import {
	formatExactTimestamp,
	formatRelativeTimestamp,
	type TimestampPrecision,
} from "./timestamp-format";

export function TimestampText({
	relative,
	exact,
	className,
	precision,
	children,
}: {
	relative: string;
	exact?: string | null;
	className?: string;
	precision?: TimestampPrecision;
	children?: ReactNode;
}) {
	const { showExactTimestamps, timestampTimezone } = useSettingsState();
	const exactTimestamp = formatExactTimestamp(exact, timestampTimezone, precision);
	const visible = formatRelativeTimestamp(
		relative,
		exact,
		showExactTimestamps,
		timestampTimezone,
		precision,
	);
	const content = children ?? visible;

	if (!exactTimestamp) {
		return <span className={className}>{content}</span>;
	}

	return (
		<Tooltip>
			<TooltipTrigger asChild>
				<span
					className={className}
					tabIndex={0}
				>
					{content}
				</span>
			</TooltipTrigger>
			<TooltipContent side="top" align="start" sideOffset={6}>
				{exactTimestamp}
			</TooltipContent>
		</Tooltip>
	);
}

export function ExactTimestampText({
	value,
	className,
	precision,
}: {
	value: string;
	className?: string;
	precision?: TimestampPrecision;
}) {
	const { timestampTimezone } = useSettingsState();
	const formatted = formatExactTimestamp(value, timestampTimezone, precision) ?? value;

	return (
		<TimestampText
			relative={formatted}
			exact={value}
			className={className}
			precision={precision}
		>
			{formatted}
		</TimestampText>
	);
}

// src/components/TimestampText.svelte
<script lang="ts">
	import { settingsStore } from "@/lib/settings-store";
	import {
		formatExactTimestamp,
		formatRelativeTimestamp,
		type TimestampPrecision,
	} from "./timestamp-format";

	let {
		value,
		relative,
		precision = "minute",
		fallback = "—",
		class: className = "",
	}: {
		value?: string | null;
		relative?: string | null;
		precision?: TimestampPrecision;
		fallback?: string;
		class?: string;
	} = $props();

	const exactTimestamp = $derived(
		formatExactTimestamp(value, $settingsStore.timestampTimezone, precision),
	);
	const display = $derived(
		relative
			? formatRelativeTimestamp(
					relative,
					value,
					$settingsStore.showExactTimestamps,
					$settingsStore.timestampTimezone,
					precision,
				)
			: (exactTimestamp ?? value ?? fallback),
	);
</script>

{#if value}
	<time
		datetime={value}
		title={value}
		aria-label={`${display}. Exact timestamp ${value}`}
		class={className}
	>{display}</time>
{:else}
	<span class={className}>{relative ?? fallback}</span>
{/if}
