// src/components/ui/separator.tsx
import type * as React from "react"
import { Separator as SeparatorPrimitive } from "radix-ui"

import { cnfast } from "@/lib/utils"

function Separator({
  className,
  orientation = "horizontal",
  decorative = true,
  ...props
}: React.ComponentProps<typeof SeparatorPrimitive.Root>) {
  return (
    <SeparatorPrimitive.Root
      data-slot="separator"
      decorative={decorative}
      orientation={orientation}
      className={cnfast(
        "shrink-0 bg-border data-horizontal:h-px data-horizontal:w-full data-vertical:w-px data-vertical:self-stretch",
        className
      )}
      {...props}
    />
  )
}

export { Separator }

// .conflict-side-0/src/components/ui/svelte/Separator.svelte
<script lang="ts">
	import { cnfast } from "@/lib/utils";
	import type { UiProps } from "./types";

	let {
		class: className = "",
		orientation = "horizontal",
		decorative = true,
		...rest
	}: UiProps & {
		orientation?: "horizontal" | "vertical";
		decorative?: boolean;
	} = $props();
</script>

<div
	data-slot="separator"
	data-orientation={orientation}
	data-horizontal={orientation === "horizontal" ? "" : undefined}
	data-vertical={orientation === "vertical" ? "" : undefined}
	role={decorative ? "presentation" : "separator"}
	aria-orientation={decorative ? undefined : orientation}
	class={cnfast(
		"shrink-0 bg-border data-horizontal:h-px data-horizontal:w-full data-vertical:w-px data-vertical:self-stretch",
		className,
	)}
	{...rest}
></div>
