// src/features/command-palette/CommandPalette.tsx
import { useMemo, useState } from "react";
import { Box, Folder, PanelsTopLeft } from "lucide-react";
import {
	CommandDialog,
	CommandEmpty,
	CommandGroup,
	CommandInput,
	CommandItem,
	CommandList,
} from "@/components/ui/command";
import { filterResourceSearchIndex } from "@/features/resources";
import { useDashboardState } from "@/lib/hooks";
import { makeNamespaceNode } from "@/lib/tree-nav";
import type { ResourceSummary } from "@/lib/types";
import type { SavedWorkspace } from "@/lib/workspaces";
import type { AppNavigation } from "@/app/useAppNavigation";
import {
	buildNavigationEntries,
	filterNamespaces,
	filterNavigationEntries,
	resourceEntryKey,
	type PaletteNavigationEntry,
} from "./entries";
import { useCommandPaletteStore } from "./store";
import { useCommandPaletteShortcut } from "./useCommandPaletteShortcut";
import { useResourceSearchEntries } from "./useResourceSearchEntries";

const RESOURCE_RESULT_CAP = 50;
const NAMESPACE_RESULT_CAP = 8;

interface CommandPaletteProps {
	clusterContext: string;
	kubeconfigEnvVar?: string;
	workspace: SavedWorkspace | null;
	navigation: AppNavigation;
	onSelectResource: (resource: ResourceSummary) => void;
}

export function CommandPalette({
	clusterContext,
	kubeconfigEnvVar,
	workspace,
	navigation,
	onSelectResource,
}: CommandPaletteProps) {
	useCommandPaletteShortcut();
	const open = useCommandPaletteStore((state) => state.open);
	const setOpen = useCommandPaletteStore((state) => state.setOpen);
	const argoDetected = useDashboardState().argoDetected;
	const [query, setQuery] = useState("");

	const { index, namespaces } = useResourceSearchEntries({
		open,
		clusterContext,
		kubeconfigEnvVar,
		workspace,
	});

	const navigationEntries = useMemo(
		() => buildNavigationEntries(argoDetected),
		[argoDetected],
	);
	const visibleNavigation = useMemo(
		() => filterNavigationEntries(navigationEntries, query),
		[navigationEntries, query],
	);
	const hasQuery = query.trim().length > 0;
	const visibleNamespaces = useMemo(
		() =>
			hasQuery
				? filterNamespaces(namespaces, query).slice(0, NAMESPACE_RESULT_CAP)
				: [],
		[hasQuery, namespaces, query],
	);
	const visibleResources = useMemo(
		() =>
			hasQuery
				? filterResourceSearchIndex(index, query, "").slice(
						0,
						RESOURCE_RESULT_CAP,
					)
				: [],
		[hasQuery, index, query],
	);

	const close = () => {
		setOpen(false);
		setQuery("");
	};

	const handleOpenChange = (next: boolean) => {
		setOpen(next);
		if (!next) setQuery("");
	};

	const selectNavigation = (entry: PaletteNavigationEntry) => {
		close();
		if (entry.action === "settings") {
			navigation.handleOpenSettings();
		} else if (entry.action === "launcher") {
			navigation.handleOpenLauncher();
		} else if (entry.nodeId) {
			navigation.handleTreeNodeSelect(entry.nodeId);
		}
	};

	const selectNamespace = (namespace: string) => {
		close();
		navigation.handleTreeNodeSelect(makeNamespaceNode(namespace).id);
	};

	const selectResource = (resource: ResourceSummary) => {
		close();
		onSelectResource(resource);
	};

	return (
		<CommandDialog
			open={open}
			onOpenChange={handleOpenChange}
			title="Search"
			description="Search views, namespaces, and resources"
			commandProps={{ shouldFilter: false }}
		>
			<CommandInput
				placeholder="Search views, namespaces, and resources..."
				value={query}
				onValueChange={setQuery}
			/>
			<CommandList>
				<CommandEmpty>No results found.</CommandEmpty>
				{visibleResources.length > 0 && (
					<CommandGroup heading="Resources">
						{visibleResources.map((resource) => (
							<CommandItem
								key={resourceEntryKey(resource)}
								value={resourceEntryKey(resource)}
								onSelect={() => selectResource(resource)}
							>
								<Box className="shrink-0 text-muted-foreground" />
								<span className="truncate">{resource.name}</span>
								<span className="ml-auto flex shrink-0 items-center gap-2 text-[10px] text-muted-foreground">
									{resource.namespace && <span>{resource.namespace}</span>}
									<span>{resource.kind}</span>
								</span>
							</CommandItem>
						))}
					</CommandGroup>
				)}
				{visibleNamespaces.length > 0 && (
					<CommandGroup heading="Namespaces">
						{visibleNamespaces.map((namespace) => (
							<CommandItem
								key={`namespace:${namespace}`}
								value={`namespace:${namespace}`}
								onSelect={() => selectNamespace(namespace)}
							>
								<Folder className="shrink-0 text-muted-foreground" />
								<span className="truncate">{namespace}</span>
							</CommandItem>
						))}
					</CommandGroup>
				)}
				{visibleNavigation.length > 0 && (
					<CommandGroup heading="Go to">
						{visibleNavigation.map((entry) => (
							<CommandItem
								key={entry.id}
								value={entry.id}
								onSelect={() => selectNavigation(entry)}
							>
								<PanelsTopLeft className="shrink-0 text-muted-foreground" />
								<span className="truncate">{entry.label}</span>
							</CommandItem>
						))}
					</CommandGroup>
				)}
			</CommandList>
		</CommandDialog>
	);
}

// src/app/svelte/CommandPalette.svelte
<script lang="ts">
	import { createQuery, useQueryClient } from "@tanstack/svelte-query";
	import { onMount } from "svelte";
	import { Box, Folder, PanelsTopLeft } from "lucide-svelte";
	import {
		CommandDialog,
		CommandEmpty,
		CommandGroup,
		CommandInput,
		CommandItem,
		CommandList,
	} from "@/components/ui/svelte";
	import {
		buildDedupedResourceSearchIndex,
		buildGlobalSearchFetchKeys,
		buildNavigationEntries,
		filterNamespaces,
		filterNavigationEntries,
		resourceEntryKey,
		type PaletteNavigationEntry,
	} from "@/features/command-palette/entries";
	import { shouldToggleCommandPaletteShortcut } from "@/features/command-palette/shortcut";
	import {
		fetchResourcePage,
		filterResourceSearchIndex,
	} from "@/features/resources";
	import {
		createTauriClient,
		detectArgoCD,
		detectFlux,
		listNamespaces,
	} from "@/lib/tauri";
	import { queryKeys } from "@/lib/queryKeys";
	import { kubeconfigSourceKey as normalizeKubeconfigSourceKey } from "@/lib/settings";
	import {
		makeNamespaceNode,
		type TreeNodeId,
	} from "@/lib/tree-nav";
	import type { DiscoveredResourceKind, ResourceSummary } from "@/lib/types";
	import type { SavedWorkspace } from "@/lib/workspace-model";
	import type { WorkspaceReadContext } from "@/lib/workspaceReadContext";
	import { settingsStore } from "@/lib/settings-store";
	import { treeNodeForResource } from "./workspaceNavigation";

	const RESOURCE_RESULT_CAP = 50;
	const NAMESPACE_RESULT_CAP = 8;

	let {
	open = $bindable(false),
	workspace,
	workspaceReadContext,
	presentCustomResourceKinds,
	onNodeSelect,
	onResourceSelect,
	onOpenLauncher,
	onOpenSettings,
}: {
	open: boolean;
	workspace: SavedWorkspace;
	workspaceReadContext: WorkspaceReadContext;
	presentCustomResourceKinds: DiscoveredResourceKind[];
	onNodeSelect: (id: TreeNodeId) => void;
	onResourceSelect: (resource: ResourceSummary, id: TreeNodeId) => void;
	onOpenLauncher: () => void;
	onOpenSettings: () => void;
} = $props();

	const client = createTauriClient();
	const queryClient = useQueryClient();
	let query = $state("");
	const showUnavailableGitOpsProviders = $derived(
		$settingsStore.showUnavailableGitOpsProviders,
	);

	const sourceReady = $derived(workspaceReadContext.sourceReady);
	const kubeconfigSourceKey = $derived(workspaceReadContext.kubeconfigSourceKey);
	const normalizedSourceKey = $derived(normalizeKubeconfigSourceKey(kubeconfigSourceKey));
	const namespacesQuery = createQuery<string[]>(() => ({
		queryKey: queryKeys.namespaces(workspace.scope.clusterContext, kubeconfigSourceKey),
		queryFn: async () =>
			(await listNamespaces(client, workspace.scope.clusterContext, kubeconfigSourceKey)).map(
				(namespace) => namespace.name,
			),
		enabled: open && sourceReady,
		staleTime: 30_000,
		retry: false,
	}));

	const argoDetectionQuery = createQuery<boolean>(() => ({
		queryKey: queryKeys.argoDetect(workspace.scope.clusterContext, kubeconfigSourceKey),
		queryFn: () => detectArgoCD(client, workspace.scope.clusterContext, kubeconfigSourceKey),
		enabled: open && sourceReady,
		staleTime: 60_000,
	}));

	const fluxDetectionQuery = createQuery(() => ({
		queryKey: queryKeys.fluxDetect(workspace.scope.clusterContext, kubeconfigSourceKey),
		queryFn: () => detectFlux(client, workspace.scope.clusterContext, kubeconfigSourceKey),
		enabled: open && sourceReady,
		staleTime: 60_000,
	}));
	const gitOpsDetectionReady = $derived(
		!argoDetectionQuery.isPending && !fluxDetectionQuery.isPending,
	);
	const fetchKeys = $derived(
		buildGlobalSearchFetchKeys(
			workspace.scope.namespaces,
			presentCustomResourceKinds,
			argoDetectionQuery.data === true,
			fluxDetectionQuery.data?.kinds ?? [],
		),
	);
	const resourcesQuery = createQuery<ResourceSummary[]>(() => ({
		queryKey: queryKeys.resources(workspace.scope.clusterContext, fetchKeys, kubeconfigSourceKey),
		queryFn: () => fetchResourcePage(workspace.scope.clusterContext, fetchKeys, kubeconfigSourceKey),
		enabled: open && sourceReady && gitOpsDetectionReady && fetchKeys.length > 0,
		staleTime: 30_000,
	}));

	const gitOpsNavigationVisible = $derived(
		argoDetectionQuery.data === true ||
			fluxDetectionQuery.data?.detected === true ||
			showUnavailableGitOpsProviders,
	);
	const navigationEntries = $derived(buildNavigationEntries(gitOpsNavigationVisible));
	const hasQuery = $derived(query.trim().length > 0);
	const visibleNavigation = $derived(filterNavigationEntries(navigationEntries, query));
	const visibleNamespaces = $derived(
		hasQuery
			? filterNamespaces(namespacesQuery.data ?? [], query).slice(0, NAMESPACE_RESULT_CAP)
			: [],
	);
	const resourceSearchIndex = $derived.by(() => {
		if (!open) return [];
		const warmedRows = resourcesQuery.data ?? [];
		const cached = queryClient.getQueriesData<ResourceSummary[]>({
			queryKey: ["resources", normalizedSourceKey, workspace.scope.clusterContext],
		});
		return buildDedupedResourceSearchIndex([
			warmedRows,
			...cached.map(([, rows]) => rows ?? []),
		]);
	});
	const visibleResources = $derived(
		hasQuery
			? filterResourceSearchIndex(resourceSearchIndex, query, "").slice(0, RESOURCE_RESULT_CAP)
			: [],
	);
	const hasResults = $derived(
		visibleNavigation.length > 0 || visibleNamespaces.length > 0 || visibleResources.length > 0,
	);

	onMount(() => {
		const handler = (event: KeyboardEvent) => {
			if (!shouldToggleCommandPaletteShortcut(event)) return;
			event.preventDefault();
			event.stopPropagation();
			open = !open;
		};
		window.addEventListener("keydown", handler, { capture: true });
		return () => {
			window.removeEventListener("keydown", handler, { capture: true });
		};
	});

	function close() {
		open = false;
		query = "";
	}

	function selectNavigation(entry: PaletteNavigationEntry) {
		close();
		if (entry.action === "settings") onOpenSettings();
		else if (entry.action === "launcher") onOpenLauncher();
		else if (entry.nodeId) onNodeSelect(entry.nodeId);
	}

	function selectNamespace(namespace: string) {
		close();
		onNodeSelect(makeNamespaceNode(namespace).id);
	}

	function selectResource(resource: ResourceSummary) {
		close();
		onResourceSelect(resource, treeNodeForResource(resource));
	}

</script>

<CommandDialog
	{open}
	onOpenChange={(next: boolean) => {
		open = next;
		if (!next) query = "";
	}}
	title="Search"
	description="Search views, namespaces, and resources"
	commandProps={{ shouldFilter: false }}
>
	<CommandInput
		value={query}
		oninput={(event: Event) => {
			query = event.currentTarget instanceof HTMLInputElement ? event.currentTarget.value : "";
		}}
		placeholder="Search views, namespaces, and resources..."
	/>
	<CommandList>
		{#if !hasResults}
			<CommandEmpty>No results found.</CommandEmpty>
		{/if}
		{#if visibleResources.length > 0}
			<CommandGroup heading="Resources">
				{#each visibleResources as resource}
					<CommandItem value={resourceEntryKey(resource)} onSelect={() => selectResource(resource)}>
						<Box class="shrink-0 text-muted-foreground" />
						<span class="truncate">{resource.name}</span>
						<span class="ml-auto flex shrink-0 items-center gap-2 text-xs text-muted-foreground">
							<span>{resource.cluster}</span>
							{#if resource.namespace}<span>{resource.namespace}</span>{/if}
							<span>{resource.kind}</span>
						</span>
					</CommandItem>
				{/each}
			</CommandGroup>
		{/if}
		{#if visibleNamespaces.length > 0}
			<CommandGroup heading="Namespaces">
				{#each visibleNamespaces as namespace}
					<CommandItem value={`namespace:${namespace}`} onSelect={() => selectNamespace(namespace)}>
						<Folder class="shrink-0 text-muted-foreground" />
						<span class="truncate">{namespace}</span>
					</CommandItem>
				{/each}
			</CommandGroup>
		{/if}
		{#if visibleNavigation.length > 0}
			<CommandGroup heading="Go to">
				{#each visibleNavigation as entry}
					<CommandItem value={entry.id} onSelect={() => selectNavigation(entry)}>
						<PanelsTopLeft class="shrink-0 text-muted-foreground" />
						<span class="truncate">{entry.label}</span>
					</CommandItem>
				{/each}
			</CommandGroup>
		{/if}
	</CommandList>
</CommandDialog>
