// src/app/DetailPanelFrame.tsx
import { useCallback, useState, type ReactNode } from "react";

const DETAIL_PANEL_DEFAULT_WIDTH = 480;
const DETAIL_PANEL_MIN_WIDTH = 390;
const MAIN_PANEL_MIN_WIDTH = 360;
const SIDEBAR_WIDTH = 260;

function clampDetailPanelWidth(width: number): number {
	const viewportWidth =
		typeof window === "undefined" ? 1440 : window.innerWidth;
	const maxWidth = Math.max(
		DETAIL_PANEL_MIN_WIDTH,
		viewportWidth - SIDEBAR_WIDTH - MAIN_PANEL_MIN_WIDTH,
	);
	return Math.min(Math.max(width, DETAIL_PANEL_MIN_WIDTH), maxWidth);
}

export function DetailPanelFrame({
	mainContent,
	detailPanel,
}: {
	mainContent: ReactNode;
	detailPanel: ReactNode;
}) {
	const [detailPanelWidth, setDetailPanelWidth] = useState(
		DETAIL_PANEL_DEFAULT_WIDTH,
	);

	const handleDetailResizeStart = useCallback(
		(event: React.PointerEvent<HTMLDivElement>) => {
			event.preventDefault();
			const startX = event.clientX;
			const startWidth = detailPanelWidth;

			const handlePointerMove = (moveEvent: PointerEvent) => {
				const nextWidth = startWidth + startX - moveEvent.clientX;
				setDetailPanelWidth(clampDetailPanelWidth(nextWidth));
			};

			const handlePointerUp = () => {
				document.body.style.cursor = "";
				document.body.style.userSelect = "";
				window.removeEventListener("pointermove", handlePointerMove);
				window.removeEventListener("pointerup", handlePointerUp);
			};

			document.body.style.cursor = "col-resize";
			document.body.style.userSelect = "none";
			window.addEventListener("pointermove", handlePointerMove);
			window.addEventListener("pointerup", handlePointerUp, { once: true });
		},
		[detailPanelWidth],
	);

	if (!detailPanel) return mainContent;

	return (
		<div className="flex min-w-0 flex-1 overflow-hidden">
			<div className="min-w-0 flex-1 overflow-hidden">{mainContent}</div>
			<div
				role="separator"
				aria-orientation="vertical"
				aria-label="Resize details panel"
				className="group relative flex w-2 shrink-0 cursor-col-resize items-center justify-center"
				onPointerDown={handleDetailResizeStart}
				onDoubleClick={() => setDetailPanelWidth(DETAIL_PANEL_DEFAULT_WIDTH)}
			>
				<div className="h-full w-px bg-border transition-colors group-hover:bg-ring" />
				<div className="absolute h-8 w-1 rounded-full bg-border transition-colors group-hover:bg-ring" />
			</div>
			<div
				className="h-full shrink-0 overflow-hidden"
				style={{
					width: clampDetailPanelWidth(detailPanelWidth),
					minWidth: DETAIL_PANEL_MIN_WIDTH,
				}}
			>
				{detailPanel}
			</div>
		</div>
	);
}

// src/app/svelte/DetailPanelFrame.svelte
<script lang="ts">
	import { onMount, type Snippet } from "svelte";
	import { cn } from "@/lib/utils";
	import {
		detailPanelSizeFromKey,
		detailPanelSizeFromPointer,
		DETAIL_PANEL_DEFAULT_SIZE,
		DETAIL_PANEL_MIN_SIZE,
		MAIN_PANEL_MIN_SIZE,
	} from "./detailPanelFrameModel";

	let {
		detailOpen = false,
		class: className = "",
		children,
		detailPanel,
	}: {
		detailOpen?: boolean;
		class?: string;
		children?: Snippet;
		detailPanel?: Snippet;
	} = $props();

	let frameElement = $state<HTMLDivElement | null>(null);
	let detailSize = $state(DETAIL_PANEL_DEFAULT_SIZE);
	let stopResize: (() => void) | null = null;
	const mainSize = $derived(100 - detailSize);

	onMount(() => () => stopCurrentResize());

	function stopCurrentResize() {
		if (!stopResize) return;
		stopResize();
		stopResize = null;
	}

	function startResize(event: PointerEvent) {
		if (!frameElement) return;
		event.preventDefault();
		stopCurrentResize();
		const handleMove = (moveEvent: PointerEvent) => {
			if (!frameElement) return;
			detailSize = detailPanelSizeFromPointer(
				frameElement.getBoundingClientRect(),
				moveEvent.clientX,
			);
		};
		const handleEnd = () => stopCurrentResize();
		window.addEventListener("pointermove", handleMove);
		window.addEventListener("pointerup", handleEnd);
		window.addEventListener("pointercancel", handleEnd);
		stopResize = () => {
			window.removeEventListener("pointermove", handleMove);
			window.removeEventListener("pointerup", handleEnd);
			window.removeEventListener("pointercancel", handleEnd);
		};
	}

	function handleResizeKeydown(event: KeyboardEvent) {
		const nextSize = detailPanelSizeFromKey(detailSize, event.key);
		if (nextSize === null) return;
		event.preventDefault();
		detailSize = nextSize;
	}
</script>

{#if !detailOpen || !detailPanel}
	<div class={cn("h-full min-h-0 flex-1 overflow-hidden", className)}>
		{@render children?.()}
	</div>
{:else}
	<div bind:this={frameElement} class={cn("flex h-full min-h-0 flex-1 overflow-hidden", className)}>
		<section class="h-full min-w-0 overflow-hidden" style={`flex: 0 0 ${mainSize}%;`}>
			{@render children?.()}
		</section>
		<!-- svelte-ignore a11y_no_noninteractive_tabindex, a11y_no_noninteractive_element_interactions -->
		<div
			role="separator"
			aria-label="Resize details panel"
			aria-orientation="vertical"
			aria-valuemin={DETAIL_PANEL_MIN_SIZE}
			aria-valuemax={100 - MAIN_PANEL_MIN_SIZE}
			aria-valuenow={Math.round(detailSize)}
			tabindex="0"
			class="group relative flex w-2 shrink-0 cursor-col-resize items-center justify-center bg-transparent outline-none focus-visible:bg-border/50"
			onpointerdown={startResize}
			onkeydown={handleResizeKeydown}
		>
			<div class="h-full w-px bg-border/70 group-hover:bg-border"></div>
			<div class="absolute h-8 w-1 rounded-full bg-border opacity-70"></div>
		</div>
		<aside
			class="h-full min-w-0 overflow-hidden border-l bg-surface-1"
			style={`flex: 0 0 ${detailSize}%;`}
		>
			{@render detailPanel?.()}
		</aside>
	</div>
{/if}
