// src/features/app-updates/UpdateStatusButton.tsx
import { useEffect, useMemo, useState } from "react";
import {
	AlertTriangle,
	CheckCircle2,
	Download,
	RefreshCw,
	RotateCw,
	X,
} from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
	Popover,
	PopoverContent,
	PopoverTrigger,
} from "@/components/ui/popover";
import {
	Tooltip,
	TooltipContent,
	TooltipTrigger,
} from "@/components/ui/tooltip";
import { isAppUpdatesEnabled } from "@/lib/release-channel";
import { cn } from "@/lib/utils";
import { useAppUpdateStore } from "./store";

function formatCheckedAt(value: string | null): string {
	if (!value) return "Not checked yet";
	const date = new Date(value);
	if (Number.isNaN(date.getTime())) return "Not checked yet";
	return new Intl.DateTimeFormat(undefined, {
		dateStyle: "medium",
		timeStyle: "short",
	}).format(date);
}

export function UpdateStatusButton() {
	const updatesEnabled = isAppUpdatesEnabled();
	const {
		status,
		currentVersion,
		availableVersion,
		releaseNotes,
		downloadProgress,
		lastCheckedAt,
		errorMessage,
		dismissedVersion,
		checkForUpdates,
		installUpdate,
		relaunchApp,
		dismissUpdate,
	} = useAppUpdateStore();
	const [open, setOpen] = useState(false);
	const hasUpdate = status === "available" || status === "downloading";
	const shouldAutoOpen =
		updatesEnabled &&
		status === "available" &&
		availableVersion !== null &&
		dismissedVersion !== availableVersion;

	useEffect(() => {
		if (shouldAutoOpen) setOpen(true);
	}, [shouldAutoOpen]);

	const tooltip = useMemo(() => {
		if (status === "available") return "Update available";
		if (status === "downloading") return "Downloading update";
		if (status === "installed") return "Restart to finish update";
		if (status === "error") return "Update check failed";
		if (status === "checking") return "Checking for updates";
		return "Check for updates";
	}, [status]);

	if (!updatesEnabled) return null;

	return (
		<Popover open={open} onOpenChange={setOpen}>
			<Tooltip>
				<TooltipTrigger asChild>
					<PopoverTrigger asChild>
						<Button
							type="button"
							variant="ghost"
							size="icon"
							className="relative mr-1 size-8 text-muted-foreground [-webkit-app-region:no-drag]"
							aria-label={tooltip}
						>
							<RotateCw
								className={cn(status === "checking" && "animate-spin")}
							/>
							{(hasUpdate || status === "installed") && (
								<span className="absolute right-1 top-1 size-2 rounded-full bg-primary" />
							)}
						</Button>
					</PopoverTrigger>
				</TooltipTrigger>
				<TooltipContent>{tooltip}</TooltipContent>
			</Tooltip>
			<PopoverContent align="end" className="flex flex-col gap-3">
				<div className="flex items-start justify-between gap-3">
					<div className="min-w-0">
						<div className="text-sm font-semibold text-foreground">
							App updates
						</div>
						<div className="mt-1 text-xs text-muted-foreground">
							Current version {currentVersion}
						</div>
					</div>
					{availableVersion && <Badge variant="secondary">{availableVersion}</Badge>}
				</div>

				{status === "available" && (
					<div className="flex flex-col gap-3">
						<div className="text-sm text-foreground">
							KubeCove {availableVersion} is available.
						</div>
						{releaseNotes && (
							<div className="max-h-28 overflow-y-auto rounded-sm border bg-muted/40 p-2 text-xs leading-relaxed text-muted-foreground">
								{releaseNotes}
							</div>
						)}
						<div className="flex justify-end gap-2">
							<Button
								type="button"
								variant="ghost"
								onClick={() => {
									if (availableVersion) dismissUpdate(availableVersion);
									setOpen(false);
								}}
							>
								<X data-icon="inline-start" />
								Later
							</Button>
							<Button type="button" onClick={() => void installUpdate()}>
								<Download data-icon="inline-start" />
								Install
							</Button>
						</div>
					</div>
				)}

				{status === "downloading" && (
					<div className="flex flex-col gap-2">
						<div className="text-sm text-foreground">Downloading update...</div>
						<div className="h-2 overflow-hidden rounded-full bg-muted">
							<div
								className="h-full bg-primary transition-all"
								style={{ width: `${downloadProgress ?? 12}%` }}
							/>
						</div>
						<div className="text-xs text-muted-foreground">
							{downloadProgress === null
								? "Preparing installer"
								: `${downloadProgress}%`}
						</div>
					</div>
				)}

				{status === "installed" && (
					<div className="flex flex-col gap-3">
						<div className="flex items-center gap-2 text-sm text-foreground">
							<CheckCircle2 data-icon="inline-start" />
							Update installed. Restart KubeCove to finish.
						</div>
						<Button type="button" onClick={() => void relaunchApp()}>
							<RefreshCw data-icon="inline-start" />
							Relaunch
						</Button>
					</div>
				)}

				{status === "upToDate" && (
					<div className="flex items-center gap-2 text-sm text-muted-foreground">
						<CheckCircle2 data-icon="inline-start" />
						KubeCove is up to date.
					</div>
				)}

				{status === "error" && (
					<div className="flex flex-col gap-2">
						<div className="flex items-center gap-2 text-sm text-destructive">
							<AlertTriangle data-icon="inline-start" />
							Update check failed.
						</div>
						{errorMessage && (
							<div className="text-xs leading-relaxed text-muted-foreground">
								{errorMessage}
							</div>
						)}
					</div>
				)}

				{(status === "idle" || status === "checking") && (
					<div className="text-sm text-muted-foreground">
						{status === "checking" ? "Checking for updates..." : "Ready to check."}
					</div>
				)}

				<div className="flex items-center justify-between gap-3 border-t pt-3">
					<div className="text-xs text-muted-foreground">
						Last checked: {formatCheckedAt(lastCheckedAt)}
					</div>
					<Button
						type="button"
						variant="outline"
						size="sm"
						disabled={status === "checking" || status === "downloading"}
						onClick={() => void checkForUpdates({ manual: true })}
					>
						<RefreshCw data-icon="inline-start" />
						Check
					</Button>
				</div>
			</PopoverContent>
		</Popover>
	);
}

// src/app/svelte/UpdateStatusButton.svelte
<script lang="ts">
	import {
		AlertTriangle,
		CheckCircle2,
		Download,
		RefreshCw,
		RotateCw,
		X,
	} from "lucide-svelte";
	import { Badge, Button, Popover, PopoverContent, PopoverTrigger, buttonClass } from "@/components/ui/svelte";
	import { isAppUpdatesEnabled } from "@/lib/release-channel";
	import { cnfast } from "@/lib/utils";
	import type { AppUpdateState } from "@/features/app-updates/store";
	import { appUpdateStore } from "./appUpdateStore";

	const checkedAtFormatter = new Intl.DateTimeFormat(undefined, {
		dateStyle: "medium",
		timeStyle: "short",
	});
	const updatesEnabled = isAppUpdatesEnabled();
	const update = $derived($appUpdateStore);
	let autoOpenedVersion = $state<string | null>(null);
	let panelOpen = $state(false);

	const hasUpdate = $derived(update.status === "available" || update.status === "downloading");
	const autoOpenVersion = $derived(
		updatesEnabled &&
			update.status === "available" &&
			update.availableVersion !== null &&
			update.dismissedVersion !== update.availableVersion
			? update.availableVersion
			: null,
	);
	const tooltip = $derived(updateTooltip(update));

	$effect(() => {
		if (autoOpenVersion !== null && autoOpenedVersion !== autoOpenVersion) panelOpen = true;
	});

	function formatCheckedAt(value: string | null): string {
		if (!value) return "Not checked yet";
		const date = new Date(value);
		return Number.isNaN(date.getTime()) ? "Not checked yet" : checkedAtFormatter.format(date);
	}

	function updateTooltip(state: AppUpdateState): string {
		if (state.status === "available") return "Update available";
		if (state.status === "downloading") return "Downloading update";
		if (state.status === "installed") return "Restart to finish update";
		if (state.status === "error") return "Update check failed";
		if (state.status === "checking") return "Checking for updates";
		return "Check for updates";
	}

	function closePanel() {
		panelOpen = false;
		if (update.availableVersion !== null) autoOpenedVersion = update.availableVersion;
	}

	function handlePanelOpenChange(open: boolean) {
		if (!open && update.availableVersion !== null) autoOpenedVersion = update.availableVersion;
	}

	function dismissAvailableUpdate() {
		if (update.availableVersion) update.dismissUpdate(update.availableVersion);
		closePanel();
	}
</script>

{#if updatesEnabled}
	<div class="relative mr-1 [-webkit-app-region:no-drag]">
		<Popover bind:open={panelOpen} onOpenChange={handlePanelOpenChange}>
			<PopoverTrigger
			type="button"
			class={buttonClass({
				variant: "ghost",
				size: "icon",
				className: "relative size-8 text-muted-foreground",
			})}
			title={tooltip}
			aria-label={tooltip}
			aria-expanded={panelOpen}
		>
			<RotateCw class={cnfast(update.status === "checking" && "animate-spin")} />
			{#if hasUpdate || update.status === "installed"}
				<span class="absolute right-1 top-1 size-2 rounded-full bg-primary"></span>
			{/if}
			</PopoverTrigger>

			<PopoverContent
				align="end"
				class="flex w-80 max-w-[calc(100vw-1rem)] flex-col gap-3"
				role="dialog"
				aria-label="App updates"
			>
				<div class="flex items-start justify-between gap-3">
					<div class="min-w-0">
						<div class="text-sm font-semibold text-foreground">App updates</div>
						<div class="mt-1 text-xs text-muted-foreground">Current version {update.currentVersion}</div>
					</div>
					{#if update.availableVersion}
						<Badge variant="secondary">{update.availableVersion}</Badge>
					{/if}
				</div>

				{#if update.status === "available"}
					<div class="flex flex-col gap-3">
						<div class="text-sm text-foreground">KubeCove {update.availableVersion} is available.</div>
						{#if update.releaseNotes}
							<div
								class="max-h-28 overflow-y-auto rounded-sm border bg-muted/40 p-2 text-xs leading-relaxed text-muted-foreground"
							>
								{update.releaseNotes}
							</div>
						{/if}
						<div class="flex justify-end gap-2">
							<Button type="button" variant="ghost" onclick={dismissAvailableUpdate}>
								<X data-icon="inline-start" />
								Later
							</Button>
							<Button type="button" onclick={() => void update.installUpdate()}>
								<Download data-icon="inline-start" />
								Install
							</Button>
						</div>
					</div>
				{:else if update.status === "downloading"}
					<div class="flex flex-col gap-2">
						<div class="text-sm text-foreground">Downloading update...</div>
						<div class="h-2 overflow-hidden rounded-full bg-muted">
							<div
								class="h-full bg-primary transition-all"
								style={`width: ${update.downloadProgress ?? 12}%`}
							></div>
						</div>
						<div class="text-xs text-muted-foreground">
							{update.downloadProgress === null ? "Preparing installer" : `${update.downloadProgress}%`}
						</div>
					</div>
				{:else if update.status === "installed"}
					<div class="flex flex-col gap-3">
						<div class="flex items-center gap-2 text-sm text-foreground">
							<CheckCircle2 data-icon="inline-start" />
							Update installed. Restart KubeCove to finish.
						</div>
						<Button type="button" onclick={() => void update.relaunchApp()}>
							<RefreshCw data-icon="inline-start" />
							Relaunch
						</Button>
					</div>
				{:else if update.status === "upToDate"}
					<div class="flex items-center gap-2 text-sm text-muted-foreground">
						<CheckCircle2 data-icon="inline-start" />
						KubeCove is up to date.
					</div>
				{:else if update.status === "error"}
					<div class="flex flex-col gap-2">
						<div class="flex items-center gap-2 text-sm text-destructive">
							<AlertTriangle data-icon="inline-start" />
							Update check failed.
						</div>
						{#if update.errorMessage}
							<div class="text-xs leading-relaxed text-muted-foreground">{update.errorMessage}</div>
						{/if}
					</div>
				{:else}
					<div class="text-sm text-muted-foreground">
						{update.status === "checking" ? "Checking for updates..." : "Ready to check."}
					</div>
				{/if}

				<div class="flex items-center justify-between gap-3 border-t pt-3">
					<div class="text-xs text-muted-foreground">
						Last checked: {formatCheckedAt(update.lastCheckedAt)}
					</div>
					<Button
						type="button"
						variant="outline"
						size="sm"
						disabled={update.status === "checking" || update.status === "downloading"}
						onclick={() => void update.checkForUpdates({ manual: true })}
					>
						<RefreshCw data-icon="inline-start" />
						Check
					</Button>
				</div>
			</PopoverContent>
		</Popover>
	</div>
{/if}
