// src/components/ui/svelte/Spinner.svelte
<script lang="ts">
	import { Loader2Icon } from "lucide-svelte";
	import { cnfast } from "@/lib/utils";
	import type { UiProps } from "./types";

	let { class: className = "", ...rest }: UiProps = $props();
</script>

<Loader2Icon
	role="status"
	aria-label="Loading"
	class={cnfast("size-4 animate-spin", className)}
	{...rest}
/>

// src/components/ui/spinner.tsx
import { cnfast } from "@/lib/utils"
import { Loader2Icon } from "lucide-react"

function Spinner({ className, ...props }: React.ComponentProps<"svg">) {
  return (
    <Loader2Icon role="status" aria-label="Loading" className={cnfast("size-4 animate-spin", className)} {...props} />
  )
}

export { Spinner }
